import mock from '../mock';
import user1 from 'src/assets/images/profile/user-1.jpg';
import user2 from 'src/assets/images/profile/user-2.jpg';
import user3 from 'src/assets/images/profile/user-3.jpg';
import user4 from 'src/assets/images/profile/user-4.jpg';
import user5 from 'src/assets/images/profile/user-5.jpg';

export const UserList = [
  {
    id: 1,
    firstname: 'Georgeanna',
    middleInitial: 'A',
    lastname: 'Ramero',
    image: user2,
    dob: '08/23/1986',
    gender: 'female',
    phone: '456-485-5623',
    email: 'qq739v47ggn@claimab.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Devolved Tangible Projection',
    ecname: 'John Ramero',
    ecrelation: 'Brother',
    ecphone: '456-123-7890',
    frequentlyContacted: true,
    starred: true,
    deleted: false,
    requests: [101, 102],
    insurance1: 'Aetna',
    insurance2: 'Humana'
  },
  {
    id: 2,
    firstname: 'Cami',
    middleInitial: 'B',
    lastname: 'Macha',
    image: user3,
    dob: '08/23/1986',
    gender: 'female',
    phone: '999-895-9652',
    email: 'Camisad@claimab.com',
    address: '76 Hamilton Ave',
    address2: '',
    city: 'Yonkers',
    state: 'NY',
    zipcode: '10705',
    notes: 'Horizontal Bi-Directional Capability',
    ecname: 'Jane Doe',
    ecrelation: 'Sister',
    ecphone: '999-123-4567',
    frequentlyContacted: false,
    starred: false,
    deleted: false,
    requests: [103],
    insurance1: 'Blue Cross',
    insurance2: 'Kaiser'
  },
  {
    id: 3,
    firstname: 'Alda',
    middleInitial: 'C',
    lastname: 'Ziemer',
    image: user4,
    dob: '08/23/1986',
    gender: 'female',
    phone: '789-854-8950',
    email: 'Ziemer234@claimab.com',
    address: '930 Fruit Ave',
    address2: '',
    city: 'Farrell',
    state: 'PA',
    zipcode: '16121',
    notes: 'Switchable Multimedia Hub',
    ecname: 'Paul Ziemer',
    ecrelation: 'Uncle',
    ecphone: '789-123-4567',
    frequentlyContacted: true,
    starred: false,
    deleted: false,
    requests: [104, 105],
    insurance1: 'Care Plus',
    insurance2: 'Tricare'
  },
  {
    id: 4,
    firstname: 'Luciano',
    middleInitial: 'D',
    lastname: 'Macpherson',
    image: user5,
    dob: '08/23/1986',
    gender: 'male',
    phone: '452-652-5230',
    email: 'Macpherson34@claimab.com',
    address: '19103 Stefani Ave',
    address2: '',
    city: 'Cerritos',
    state: 'CA',
    zipcode: '90703',
    notes: 'Versatile Web-Enabled Groupware',
    ecname: 'Maria Macpherson',
    ecrelation: 'Mother',
    ecphone: '452-654-7890',
    frequentlyContacted: false,
    starred: true,
    deleted: true,
    requests: [106],
    insurance1: 'Medicare',
    insurance2: 'Optimum'
  },
  {
    id: 5,
    firstname: 'Dalton',
    middleInitial: 'E',
    lastname: 'Paden',
    image: user1,
    dob: '08/23/1986',
    gender: 'male',
    phone: '985-985-7850',
    email: 'Dalton321@claimab.com',
    address: '3059 Edgewood Park Ct',
    address2: 'Apt 4B',
    city: 'Commerce Township',
    state: 'MI',
    zipcode: '48382',
    notes: 'Cloned 6th-Generation Access',
    ecname: 'Laura Paden',
    ecrelation: 'Wife',
    ecphone: '985-321-4567',
    frequentlyContacted: false,
    starred: false,
    deleted: false,
    requests: [107, 108],
    insurance1: 'Anthem (BCBS)',
    insurance2: 'Wellcare'
  },
  {
    id: 6,
    firstname: 'Juan',
    middleInitial: 'F',
    lastname: 'Granado',
    image: user2,
    dob: '08/23/1986',
    gender: 'male',
    phone: '230-541-5231',
    email: 'Granado567@claimab.com',
    address: '1330 N Douglas Ave',
    address2: '',
    city: 'Arlington Heights',
    state: 'IL',
    zipcode: '60004',
    notes: 'Multi-Tiered Coherent Workforce',
    ecname: 'Felipe Granado',
    ecrelation: 'Father',
    ecphone: '230-678-1234',
    frequentlyContacted: true,
    starred: false,
    deleted: true,
    requests: [109],
    insurance1: 'Medicare (Advantage Plan)',
    insurance2: 'AARP'
  },
  {
    id: 7,
    firstname: 'Reva',
    middleInitial: 'G',
    lastname: 'Allen',
    image: user3,
    dob: '08/23/1986',
    gender: 'female',
    phone: '478-582-6520',
    email: 'Allen326@claimab.com',
    address: '180 Topp Ln',
    address2: '',
    city: 'Tupelo',
    state: 'MS',
    zipcode: '38801',
    notes: 'Upgradable 6th-Generation Pricing Structure',
    ecname: 'James Allen',
    ecrelation: 'Brother',
    ecphone: '478-654-7890',
    frequentlyContacted: false,
    starred: false,
    deleted: true,
    requests: [110, 111],
    insurance1: 'Emblem',
    insurance2: 'Care Source'
  },
  {
    id: 8,
    firstname: 'Jule',
    middleInitial: 'H',
    lastname: 'Huseman',
    image: user4,
    dob: '08/23/1986',
    gender: 'female',
    phone: '123-652-2301',
    email: 'Huseman458@claimab.com',
    address: '33 Caraway Rd',
    address2: '',
    city: 'Reisterstown',
    state: 'MD',
    zipcode: '21136',
    notes: 'Optimized Dedicated Toolset',
    ecname: 'Hannah Huseman',
    ecrelation: 'Mother',
    ecphone: '123-789-4567',
    frequentlyContacted: true,
    starred: true,
    deleted: true,
    requests: [112],
    insurance1: 'Cigna',
    insurance2: 'Freedom Health'
  },
  {
    id: 9,
    firstname: 'Bridgette',
    middleInitial: 'I',
    lastname: 'Phung',
    image: user5,
    dob: '08/23/1986',
    gender: 'female',
    phone: '652-452-6521',
    email: 'Bridgette890@claimab.com',
    address: '#RR',
    address2: '',
    city: 'Bruceton Mills',
    state: 'WV',
    zipcode: '26525',
    notes: 'Right-Sized Tertiary Success',
    ecname: 'Tom Phung',
    ecrelation: 'Cousin',
    ecphone: '652-789-4561',
    frequentlyContacted: false,
    starred: true,
    deleted: true,
    requests: [113],
    insurance1: 'Health Net',
    insurance2: 'United Healthcare'
  },
  {
    id: 10,
    firstname: 'Ernest',
    middleInitial: 'J',
    lastname: 'Cousins',
    image: user2,
    dob: '08/23/1986',
    gender: 'male',
    phone: '785-985-6541',
    email: 'Ernest6543@claimab.com',
    address: '3756 Preston Street',
    address2: '',
    city: 'Wichita',
    state: 'KS',
    zipcode: '67213',
    notes: 'Progressive Systematic Application',
    ecname: 'Linda Cousins',
    ecrelation: 'Sister',
    ecphone: '785-123-6547',
    frequentlyContacted: false,
    starred: false,
    deleted: true,
    requests: [114, 115],
    insurance1: 'Simply',
    insurance2: 'Other'
  },
  {
    id: 11,
    firstname: 'Nicolette',
    middleInitial: 'K',
    lastname: 'Trapani',
    image: user1,
    dob: '08/23/1986',
    gender: 'female',
    phone: '652-632-6520',
    email: 'Nicoletteesdasd4@claimab.com',
    address: '1635 Franklin Street',
    address2: '',
    city: 'Montgomery',
    state: 'AL',
    zipcode: '36104',
    notes: 'Vision-Oriented Nextgeneration Hardware',
    ecname: 'Sarah Trapani',
    ecrelation: 'Mother',
    ecphone: '652-654-7890',
    frequentlyContacted: false,
    starred: false,
    deleted: true,
    requests: [116],
    insurance1: 'Optimum',
    insurance2: 'Wellcare'
  },
  {
    id: 12,
    firstname: 'Virginia',
    middleInitial: 'L',
    lastname: 'Bourdeau',
    image: user2,
    dob: '08/23/1986',
    gender: 'female',
    phone: '125-985-3210',
    email: 'Bourdeauerwe@claimab.com',
    address: '2595 Pearlman Avenue',
    address2: 'Suite 2A',
    city: 'New York',
    state: 'NY',
    zipcode: '10034',
    notes: 'Multi-Lateral Contextually-Based Collaboration',
    ecname: 'Ed Bourdeau',
    ecrelation: 'Brother',
    ecphone: '125-234-5678',
    frequentlyContacted: true,
    starred: false,
    deleted: false,
    requests: [117, 118],
    insurance1: 'Aetna',
    insurance2: 'Medicare'
  },
  {
    id: 13,
    firstname: 'Janita',
    middleInitial: 'M',
    lastname: 'Vogl',
    image: user3,
    dob: '08/23/1986',
    gender: 'female',
    phone: '541-521-6320',
    email: 'Janitafdaa@claimab.com',
    address: '508 Virginia Street',
    address2: '',
    city: 'Charleston',
    state: 'WV',
    zipcode: '25302',
    notes: 'Optimized Reciprocal Core',
    ecname: 'Jessica Vogl',
    ecrelation: 'Sister',
    ecphone: '541-123-4567',
    frequentlyContacted: true,
    starred: true,
    deleted: false,
    requests: [119],
    insurance1: 'Freedom Health',
    insurance2: 'Medicare (Advantage Plan)'
  },
  {
    id: 14,
    firstname: 'Jeneva',
    middleInitial: 'N',
    lastname: 'Bridgeforth',
    image: user4,
    dob: '08/23/1986',
    gender: 'female',
    phone: '975-895-5240',
    email: 'Bridgeforth564@claimab.com',
    address: '1516 Holt Street',
    address2: 'Apt B',
    city: 'West Palm Beach',
    state: 'FL',
    zipcode: '33401',
    notes: 'Distributed Scalable Database',
    ecname: 'Noah Bridgeforth',
    ecrelation: 'Father',
    ecphone: '975-123-6543',
    frequentlyContacted: true,
    starred: true,
    deleted: false,
    requests: [120, 121],
    insurance1: 'Care Plus',
    insurance2: 'Humana'
  },
  {
    id: 15,
    firstname: 'Roselia',
    middleInitial: 'O',
    lastname: 'Principe',
    image: user5,
    dob: '08/23/1986',
    gender: 'female',
    phone: '874-546-6521',
    email: 'Principe326@claimab.com',
    address: '2915 Auburn Creek Ln',
    address2: '',
    city: 'League City',
    state: 'TX',
    zipcode: '77573',
    notes: 'Digitized Content-Based Hardware',
    ecname: 'Olivia Principe',
    ecrelation: 'Daughter',
    ecphone: '874-987-6543',
    frequentlyContacted: false,
    starred: true,
    deleted: false,
    requests: [122, 123],
    insurance1: 'Cigna',
    insurance2: 'AARP'
  },
  {
    id: 16,
    firstname: 'Elvira',
    middleInitial: 'P',
    lastname: 'Hylton',
    image: user1,
    dob: '08/23/1986',
    gender: 'female',
    phone: '652-542-5200',
    email: 'Elviraoknsss@claimab.com',
    address: '2725 Cottage Rd',
    address2: '',
    city: 'Alpine',
    state: 'CA',
    zipcode: '91901',
    notes: 'Reduced Intangible Challenge',
    ecname: 'Peter Hylton',
    ecrelation: 'Spouse',
    ecphone: '652-234-7890',
    frequentlyContacted: false,
    starred: false,
    deleted: false,
    requests: [124],
    insurance1: 'United Healthcare',
    insurance2: 'Kaiser'
  },
  {
    id: 17,
    firstname: 'Margaret',
    middleInitial: 'Q',
    lastname: 'Pecor',
    image: user2,
    dob: '08/23/1986',
    gender: 'female',
    phone: '326-984-1200',
    email: 'Margaret4352@mediafire.com',
    address: '307 Hardy St',
    address2: '',
    city: 'Aberdeen',
    state: 'MS',
    zipcode: '39730',
    notes: 'Secured Impactful Project',
    ecname: 'Quinn Pecor',
    ecrelation: 'Son',
    ecphone: '326-789-6541',
    frequentlyContacted: true,
    starred: true,
    deleted: false,
    requests: [125, 126],
    insurance1: 'Tricare',
    insurance2: 'Molina'
  },
  {
    id: 18,
    firstname: 'Willena',
    middleInitial: 'R',
    lastname: 'Sugrue',
    image: user3,
    dob: '08/23/1986',
    gender: 'female',
    phone: '265-632-4521',
    email: 'Willena75637@claimab.com',
    address: '15919 Golf Club Dr',
    address2: '',
    city: 'Crosby',
    state: 'TX',
    zipcode: '77532',
    notes: 'Inverse Directional Throughput',
    ecname: 'Rick Sugrue',
    ecrelation: 'Brother',
    ecphone: '265-123-7894',
    frequentlyContacted: true,
    starred: true,
    deleted: false,
    requests: [127],
    insurance1: 'Anthem (BCBS)',
    insurance2: 'Blue Cross'
  },
  {
    id: 19,
    firstname: 'Eura',
    middleInitial: 'S',
    lastname: 'Solley',
    image: user4,
    dob: '08/23/1986',
    gender: 'female',
    phone: '645-647-4800',
    email: 'Solley6472@claimab.com',
    address: 'Po Box 144',
    address2: '',
    city: 'Rhome',
    state: 'TX',
    zipcode: '76078',
    notes: 'Organized Disintermediate Budgetary Management',
    ecname: 'Samuel Solley',
    ecrelation: 'Father',
    ecphone: '645-321-6548',
    frequentlyContacted: false,
    starred: false,
    deleted: true,
    requests: [128, 129],
    insurance1: 'Care Source',
    insurance2: 'Humana'
  },
  {
    id: 20,
    firstname: 'Velva',
    middleInitial: 'T',
    lastname: 'Brockett',
    image: user5,
    dob: '08/23/1986',
    gender: 'female',
    phone: '654-985-6520',
    email: 'Brocketterewgdb@claimab.com',
    address: '34 Fairview Ln',
    address2: '',
    city: 'Palm Coast',
    state: 'FL',
    zipcode: '32137',
    notes: 'Seamless Object-Oriented Framework',
    ecname: 'Tom Brockett',
    ecrelation: 'Brother',
    ecphone: '654-654-7891',
    frequentlyContacted: false,
    starred: true,
    deleted: true,
    requests: [130],
    insurance1: 'Simply',
    insurance2: 'Freedom Health'
  },
  {
    id: 21,
    firstname: 'Anya',
    middleInitial: 'U',
    lastname: 'Snapp',
    image: user3,
    dob: '08/23/1986',
    gender: 'female',
    phone: '456-652-3210',
    email: 'Snapp76848@claimab.com',
    address: '17919 Barney Dr',
    address2: 'Apt 4B',
    city: 'Accokeek',
    state: 'MD',
    zipcode: '20607',
    notes: 'Realigned Attitude-Oriented Standardization',
    ecname: 'Ulysses Snapp',
    ecrelation: 'Father',
    ecphone: '456-123-7890',
    frequentlyContacted: true,
    starred: false,
    deleted: false,
    requests: [131, 132],
    insurance1: 'AARP',
    insurance2: 'Cigna'
  },
  {
    id: 22,
    firstname: 'Latoria',
    middleInitial: 'V',
    lastname: 'Penaloza',
    image: user1,
    dob: '08/23/1986',
    gender: 'female',
    phone: '459-985-4520',
    email: 'Penaloza3546@claimab.com',
    address: '14 Huntington Dr',
    address2: 'Unit 5',
    city: 'Greenbrier',
    state: 'AR',
    zipcode: '72058',
    notes: 'Focused Modular Securedline',
    ecname: 'Vivian Penaloza',
    ecrelation: 'Mother',
    ecphone: '459-234-5678',
    frequentlyContacted: true,
    starred: false,
    deleted: true,
    requests: [133],
    insurance1: 'Kaiser',
    insurance2: 'Medicare'
  },
  {
    id: 23,
    firstname: 'Tamika',
    middleInitial: 'W',
    lastname: 'Inman',
    image: user2,
    dob: '08/23/1986',
    gender: 'female',
    phone: '645-978-4150',
    email: 'Tamikadfdf45@claimab.com',
    address: '1341 Mentionville Rd',
    address2: '',
    city: 'Darien',
    state: 'IL',
    zipcode: '60561',
    notes: 'Visionary Executive Initiative',
    ecname: 'Walter Inman',
    ecrelation: 'Husband',
    ecphone: '645-654-3210',
    frequentlyContacted: true,
    starred: false,
    deleted: true,
    requests: [134, 135],
    insurance1: 'Anthem (BCBS)',
    insurance2: 'Care Plus'
  },
  {
    id: 24,
    firstname: 'Erich',
    middleInitial: 'X',
    lastname: 'Aragon',
    image: user3,
    dob: '08/23/1986',
    gender: 'male',
    phone: '450-980-6520',
    email: 'Aragondfdf4567@claimab.com',
    address: '13 Pent Rd',
    address2: '',
    city: 'Branford',
    state: 'CT',
    zipcode: '06405',
    notes: 'Multi-Tiered Hybrid Groupware',
    ecname: 'Xavier Aragon',
    ecrelation: 'Brother',
    ecphone: '450-123-4567',
    frequentlyContacted: false,
    starred: false,
    deleted: true,
    requests: [136],
    insurance1: 'Medicare (Advantage Plan)',
    insurance2: 'Blue Cross'
  },
  {
    id: 25,
    firstname: 'Johanna',
    middleInitial: 'Y',
    lastname: 'Randel',
    image: user4,
    dob: '08/23/1986',
    gender: 'female',
    phone: '120-320-4520',
    email: 'Johanna456@claimab.com',
    address: '5791 S Staghorn Cholla Ct',
    address2: '',
    city: 'Apache Junction',
    state: 'AZ',
    zipcode: '85119',
    notes: 'Reduced Tangible Project',
    ecname: 'Yara Randel',
    ecrelation: 'Daughter',
    ecphone: '120-654-7890',
    frequentlyContacted: true,
    starred: true,
    deleted: true,
    requests: [137, 138],
    insurance1: 'Wellcare',
    insurance2: 'Health Net'
  },
  {
    id: 26,
    firstname: 'Victorina',
    middleInitial: 'Z',
    lastname: 'Heinze',
    image: user4,
    dob: '08/23/1986',
    gender: 'female',
    phone: '452-521-1230',
    email: 'Victorina4545@claimab.com',
    address: '69 El Molino Dr',
    address2: '',
    city: 'Clayton',
    state: 'CA',
    zipcode: '94517',
    notes: 'Enhanced Web-Enabled Info-Mediaries',
    ecname: 'Zach Heinze',
    ecrelation: 'Son',
    ecphone: '452-654-7891',
    frequentlyContacted: false,
    starred: false,
    deleted: true,
    requests: [139],
    insurance1: 'Freedom Health',
    insurance2: 'Humana'
  },
  {
    id: 27,
    firstname: 'Kiley',
    middleInitial: 'A',
    lastname: 'Light',
    image: user5,
    dob: '08/23/1986',
    gender: 'female',
    phone: '652-452-1230',
    email: 'Kileydfdfd45@claimab.com',
    address: '215 Waterfront Ct',
    address2: '',
    city: 'Noblesville',
    state: 'IN',
    zipcode: '46062',
    notes: 'Function-Based Systemic Localareanetwork',
    ecname: 'Amber Light',
    ecrelation: 'Sister',
    ecphone: '652-123-7890',
    frequentlyContacted: false,
    starred: true,
    deleted: false,
    requests: [140, 141],
    insurance1: 'Optimum',
    insurance2: 'United Healthcare'
  },
  {
    id: 28,
    firstname: 'Sanford',
    middleInitial: 'B',
    lastname: 'Delorenzo',
    image: user1,
    dob: '08/23/1986',
    gender: 'male',
    phone: '963-652-1230',
    email: 'Delorenzo3456@claimab.com',
    address: '11212 Amber Rd',
    address2: 'Unit 4',
    city: 'Manistee',
    state: 'MI',
    zipcode: '49660',
    notes: 'Reactive Transitional Archive',
    ecname: 'Bianca Delorenzo',
    ecrelation: 'Mother',
    ecphone: '963-123-4567',
    frequentlyContacted: true,
    starred: true,
    deleted: false,
    requests: [142],
    insurance1: 'Simply',
    insurance2: 'Tricare'
  },
  {
    id: 29,
    firstname: 'Hans',
    middleInitial: 'C',
    lastname: 'Strebel',
    image: user2,
    dob: '08/23/1986',
    gender: 'male',
    phone: '546-654-1230',
    email: 'Strebel345@claimab.com',
    address: '2009 W Azalea Ave',
    address2: 'Apt 3',
    city: 'Baker',
    state: 'LA',
    zipcode: '70714',
    notes: 'Operative Mobile Portal',
    ecname: 'Chris Strebel',
    ecrelation: 'Brother',
    ecphone: '546-789-1230',
    frequentlyContacted: false,
    starred: false,
    deleted: false,
    requests: [143],
    insurance1: 'Emblem',
    insurance2: 'Molina'
  },
  {
    id: 30,
    firstname: 'Roger',
    middleInitial: 'D',
    lastname: 'Trinidad',
    image: user1,
    dob: '08/23/1986',
    gender: 'male',
    phone: '123-456-7890',
    email: '3mcrz8gmymd@claimab.com',
    address: '203 Dawn Dr',
    address2: '',
    city: 'Mount Holly',
    state: 'NC',
    zipcode: '28120',
    notes: 'Fundamental Maximized Systemengine',
    ecname: 'Daphne Trinidad',
    ecrelation: 'Wife',
    ecphone: '123-789-6543',
    frequentlyContacted: false,
    starred: true,
    deleted: true,
    requests: [144, 145],
    insurance1: 'Care Source',
    insurance2: 'Anthem (BCBS)'
  }
];
mock.onGet('/api/data/users/UsersData').reply(() => {
  const users = UserList;
  return [200, JSON.parse(JSON.stringify(users))];
});
export default UserList;
