import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Mock data for pharmacists
const PharmacistList = [
  {
    id: 1,
    firstname: 'John',
    lastname: 'Doe',
    department: 'Clinical Pharmacy',
    pharmacy: 'Walgreens',
    phone: '456-485-5623',
    email: 'johndoe@pharmacy.com',
    address: '19214 110th Rd, Saint Albans, NY, 11412',
    notes: 'Specializes in oncology medication management',
    deaNumber: 'AB1234567',
    licenseNumber: 'PH12345',
    licenseExpiration: '2025-06-30',
    npiNumber: '1234567890',
    yearsOfExperience: 15,
    languagesSpoken: ['English', 'Spanish'],
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
  },
  {
    id: 2,
    firstname: 'Jane',
    lastname: 'Smith',
    department: 'Retail Pharmacy',
    pharmacy: 'CVS Health',
    phone: '999-895-9652',
    email: 'janesmith@cvs.com',
    address: '76 Hamilton Ave, Yonkers, NY, 10705',
    notes: 'Focus on chronic disease management',
    deaNumber: 'AC9876543',
    licenseNumber: 'PH67890',
    licenseExpiration: '2026-03-15',
    npiNumber: '9876543210',
    yearsOfExperience: 10,
    languagesSpoken: ['English'],
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
  },
  {
    id: 3,
    firstname: 'Albert',
    lastname: 'Johnson',
    department: 'Compounding Pharmacy',
    pharmacy: 'Custom Rx',
    phone: '789-854-8950',
    email: 'ajohnson@customrx.com',
    address: '930 Fruit Ave, Farrell, PA, 16121',
    notes: 'Expert in sterile compounding',
    deaNumber: 'BC7654321',
    licenseNumber: 'PH09876',
    licenseExpiration: '2024-11-22',
    npiNumber: '3456789012',
    yearsOfExperience: 8,
    languagesSpoken: ['English', 'French'],
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
  },
  {
    id: 4,
    firstname: 'Emily',
    lastname: 'Clark',
    department: 'Clinical Pharmacy',
    pharmacy: 'Kaiser Permanente',
    phone: '452-652-5230',
    email: 'eclark@kp.org',
    address: '19103 Stefani Ave, Cerritos, CA, 90703',
    notes: 'Specializes in pediatrics',
    deaNumber: 'CD6543210',
    licenseNumber: 'PH54321',
    licenseExpiration: '2023-09-01',
    npiNumber: '5678901234',
    yearsOfExperience: 12,
    languagesSpoken: ['English'],
    frequentlycontacted: false,
    starred: true,
    deleted: true,
    pharmacies: [201, 202],
  },
  {
    id: 5,
    firstname: 'David',
    lastname: 'Brown',
    department: 'Hospital Pharmacy',
    pharmacy: 'Mount Sinai Hospital',
    phone: '985-985-7850',
    email: 'dbrown@mountsinai.com',
    address: '3059 Edgewood Park Ct, Commerce Township, MI',
    notes: 'Focus on emergency medicine',
    deaNumber: 'EF6543219',
    licenseNumber: 'PH23456',
    licenseExpiration: '2027-01-12',
    npiNumber: '6543210987',
    yearsOfExperience: 18,
    languagesSpoken: ['English', 'German'],
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
  },
  {
    id: 6,
    firstname: 'Sophia',
    lastname: 'Davis',
    department: 'Retail Pharmacy',
    pharmacy: 'Rite Aid',
    phone: '230-541-5231',
    email: 'sdavis@riteaid.com',
    address: '1330 N Douglas Ave, Arlington Heights, IL',
    notes: 'Chronic care management specialist',
    deaNumber: 'FG8765432',
    licenseNumber: 'PH76543',
    licenseExpiration: '2025-07-25',
    npiNumber: '1230987654',
    yearsOfExperience: 14,
    languagesSpoken: ['English'],
    frequentlycontacted: true,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
  },
  {
    id: 7,
    firstname: 'Olivia',
    lastname: 'Miller',
    department: 'Retail Pharmacy',
    pharmacy: 'CVS Health',
    phone: '478-582-6520',
    email: 'omiller@cvs.com',
    address: '180 Topp Ln, Tupelo, MS',
    notes: 'Specializes in patient education',
    deaNumber: 'GH9876543',
    licenseNumber: 'PH76544',
    licenseExpiration: '2026-08-18',
    npiNumber: '1239876543',
    yearsOfExperience: 7,
    languagesSpoken: ['English', 'Spanish'],
    frequentlycontacted: false,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
  },
  {
    id: 8,
    firstname: 'Noah',
    lastname: 'Williams',
    department: 'Hospital Pharmacy',
    pharmacy: 'Cedars-Sinai Medical Center',
    phone: '123-652-2301',
    email: 'nwilliams@cedars-sinai.com',
    address: '33 Caraway Rd, Reisterstown, MD',
    notes: 'Focus on critical care pharmacy',
    deaNumber: 'HI8765432',
    licenseNumber: 'PH65432',
    licenseExpiration: '2025-12-10',
    npiNumber: '6540987654',
    yearsOfExperience: 11,
    languagesSpoken: ['English'],
    frequentlycontacted: true,
    starred: true,
    deleted: true,
    pharmacies: [201, 202],
  },
  {
    id: 9,
    firstname: 'Liam',
    lastname: 'Jones',
    department: 'Clinical Pharmacy',
    pharmacy: 'Mayo Clinic',
    phone: '652-452-6521',
    email: 'ljones@mayoclinic.org',
    address: '#RR, Bruceton Mills, WV',
    notes: 'Expert in cardiology medication',
    deaNumber: 'IJ7654321',
    licenseNumber: 'PH54322',
    licenseExpiration: '2024-04-28',
    npiNumber: '0987654321',
    yearsOfExperience: 13,
    languagesSpoken: ['English'],
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
  },
  {
    id: 10,
    firstname: 'Emma',
    lastname: 'Taylor',
    department: 'Retail Pharmacy',
    pharmacy: 'Walgreens',
    phone: '789-123-4567',
    email: 'etaylor@walgreens.com',
    address: '456 Oak St, Chicago, IL',
    notes: 'Specializes in diabetes management',
    deaNumber: 'JK1234567',
    licenseNumber: 'PH87654',
    licenseExpiration: '2026-09-15',
    npiNumber: '1122334455',
    yearsOfExperience: 9,
    languagesSpoken: ['English', 'Spanish'],
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
  },
  {
    id: 11,
    firstname: 'Ava',
    lastname: 'Anderson',
    department: 'Compounding Pharmacy',
    pharmacy: 'Custom Rx',
    phone: '555-123-4567',
    email: 'aanderson@customrx.com',
    address: '789 Pine St, Seattle, WA',
    notes: 'Expert in hormone replacement therapy',
    deaNumber: 'LM9876543',
    licenseNumber: 'PH23457',
    licenseExpiration: '2025-11-30',
    npiNumber: '2233445566',
    yearsOfExperience: 16,
    languagesSpoken: ['English'],
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
  },
  {
    id: 12,
    firstname: 'Mason',
    lastname: 'Wilson',
    department: 'Hospital Pharmacy',
    pharmacy: 'Johns Hopkins Hospital',
    phone: '410-555-1234',
    email: 'mwilson@jhmi.edu',
    address: '321 Hospital Dr, Baltimore, MD',
    notes: 'Focus on transplant medications',
    deaNumber: 'NO4567890',
    licenseNumber: 'PH34567',
    licenseExpiration: '2027-03-20',
    npiNumber: '3344556677',
    yearsOfExperience: 20,
    languagesSpoken: ['English', 'French'],
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
  },
  {
    id: 13,
    firstname: 'Isabella',
    lastname: 'Thomas',
    department: 'Retail Pharmacy',
    pharmacy: 'CVS Health',
    phone: '617-555-9876',
    email: 'ithomas@cvs.com',
    address: '654 Main St, Boston, MA',
    notes: 'Specializes in geriatric care',
    deaNumber: 'PQ7890123',
    licenseNumber: 'PH45678',
    licenseExpiration: '2024-12-31',
    npiNumber: '4455667788',
    yearsOfExperience: 11,
    languagesSpoken: ['English', 'Italian'],
    frequentlycontacted: false,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
  },
  {
    id: 14,
    firstname: 'Ethan',
    lastname: 'Jackson',
    department: 'Clinical Pharmacy',
    pharmacy: 'Cleveland Clinic',
    phone: '216-555-4321',
    email: 'ejackson@ccf.org',
    address: '987 Clinic Ave, Cleveland, OH',
    notes: 'Expert in infectious diseases',
    deaNumber: 'RS0123456',
    licenseNumber: 'PH56789',
    licenseExpiration: '2026-06-15',
    npiNumber: '5566778899',
    yearsOfExperience: 14,
    languagesSpoken: ['English'],
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
  },
  {
    id: 15,
    firstname: 'Mia',
    lastname: 'White',
    department: 'Retail Pharmacy',
    pharmacy: 'Rite Aid',
    phone: '305-555-6789',
    email: 'mwhite@riteaid.com',
    address: '123 Beach Blvd, Miami, FL',
    notes: 'Specializes in pain management',
    deaNumber: 'TU3456789',
    licenseNumber: 'PH67891',
    licenseExpiration: '2025-08-22',
    npiNumber: '6677889900',
    yearsOfExperience: 8,
    languagesSpoken: ['English', 'Spanish'],
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
  }
];

function generateMigrationSQL() {
    let sql = `-- Pharmacists Data Migration
-- Generated on ${new Date().toISOString()}
-- Total records: ${PharmacistList.length}

BEGIN;

-- Clear existing data (optional - uncomment if needed)
-- DELETE FROM pharmacists;

`;

    PharmacistList.forEach((pharmacist, index) => {
        const languagesSpoken = Array.isArray(pharmacist.languagesSpoken) 
            ? pharmacist.languagesSpoken.join(', ') 
            : pharmacist.languagesSpoken || 'English';
        
        const deleted = pharmacist.deleted ? 'true' : 'false';
        const deletedOn = pharmacist.deleted ? 'now()' : 'null';
        const deletedBy = pharmacist.deleted ? '1' : 'null';

        sql += `-- Pharmacist ${index + 1}: ${pharmacist.firstname} ${pharmacist.lastname}
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-${pharmacist.id}-${Date.now()}',
    now(),
    1,
    now(),
    1,
    ${deleted},
    ${deletedOn},
    ${deletedBy},
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    '${pharmacist.firstname}',
    null,
    '${pharmacist.lastname}',
    '${pharmacist.phone}',
    '${pharmacist.email}',
    '${pharmacist.notes || ''}',
    '${pharmacist.department?.toLowerCase().includes('clinical') ? 'clinical' : 
      pharmacist.department?.toLowerCase().includes('hospital') ? 'hospital' : 
      pharmacist.department?.toLowerCase().includes('compounding') ? 'compounding' : 'staff'}',
    '${pharmacist.deaNumber}',
    '${pharmacist.npiNumber}',
    '${pharmacist.licenseNumber}',
    '${pharmacist.licenseExpiration}',
    ${pharmacist.yearsOfExperience},
    '${languagesSpoken}'
);

`;
    });

    sql += `COMMIT;

-- Verify the migration
SELECT COUNT(*) as total_pharmacists FROM pharmacists;
SELECT COUNT(*) as active_pharmacists FROM pharmacists WHERE deleted = false;
SELECT COUNT(*) as archived_pharmacists FROM pharmacists WHERE deleted = true;

-- Show sample of administrative data
SELECT 
    id,
    first_name,
    last_name,
    created_by,
    created_on,
    updated_by,
    updated_on,
    status,
    version
FROM pharmacists 
LIMIT 5;
`;

    return sql;
}

// Generate and write the SQL file
const migrationSQL = generateMigrationSQL();

// Output SQL to console for redirection
console.log(migrationSQL);

console.log(`✅ Pharmacists migration SQL generated successfully!`);
console.log(`📊 Total pharmacists: ${PharmacistList.length}`);
console.log(`🔍 Active pharmacists: ${PharmacistList.filter(p => !p.deleted).length}`);
console.log(`🗄️  Archived pharmacists: ${PharmacistList.filter(p => p.deleted).length}`); 