import mock from '../mock';
import user1 from 'src/assets/images/profile/user-1.jpg';
import user2 from 'src/assets/images/profile/user-2.jpg';
import user3 from 'src/assets/images/profile/user-3.jpg';
import user4 from 'src/assets/images/profile/user-4.jpg';
import user5 from 'src/assets/images/profile/user-5.jpg';

export const PharmacyList = [
  {
    id: 1,
    pharmacyName: 'CVS Pharmacy #123',
    pharmacyType: 'Retail',
    phone: '800-123-4567',
    fax: '800-123-7654',
    email: 'contact@cvs123.com',
    website: 'www.cvs123.com',
    address: '19214 110th Rd, Saint Albans, NY, 11412',
    businessHours: '9 AM - 9 PM',
    licenseNumber: 'PH87654',
    licenseExpiration: '2026-03-15',
    npiNumber: '1234567890',
    insuranceAccepted: ['Medicare', 'Medicaid', 'BlueCross BlueShield'],
    servicesOffered: ['Vaccinations', 'Delivery', 'Compounding'],
    pharmacyChain: 'CVS Health',
    managerName: 'John Doe',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacists: [201, 202],
    requests: [101, 102],
  },
  {
    id: 2,
    pharmacyName: 'Walgreens #456',
    pharmacyType: 'Retail',
    phone: '888-456-7890',
    fax: '888-456-7891',
    email: 'support@walgreens456.com',
    website: 'www.walgreens456.com',
    address: '76 Hamilton Ave, Yonkers, NY, 10705',
    businessHours: '8 AM - 8 PM',
    licenseNumber: 'PH54321',
    licenseExpiration: '2025-07-11',
    npiNumber: '0987654321',
    insuranceAccepted: ['Aetna', 'Cigna', 'Medicare'],
    servicesOffered: ['Vaccinations', 'Clinical Consultations', 'Home Delivery'],
    pharmacyChain: 'Walgreens',
    managerName: 'Jane Smith',
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacists: [203],
    requests: [101, 102],
  },
  {
    id: 3,
    pharmacyName: 'Good Health Pharmacy',
    pharmacyType: 'Independent',
    phone: '789-854-8950',
    fax: '789-854-8951',
    email: 'info@goodhealthpharmacy.com',
    website: 'www.goodhealthpharmacy.com',
    address: '930 Fruit Ave, Farrell, PA, 16121',
    businessHours: '9 AM - 7 PM',
    licenseNumber: 'PH32109',
    licenseExpiration: '2024-10-22',
    npiNumber: '5678901234',
    insuranceAccepted: ['Medicaid', 'Humana', 'United Healthcare'],
    servicesOffered: ['Vaccinations', 'Specialty Medications'],
    pharmacyChain: 'Independent',
    managerName: 'Michael Johnson',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacists: [204, 205],
    requests: [101, 102],
  },
  {
    id: 4,
    pharmacyName: 'Rite Aid #789',
    pharmacyType: 'Retail',
    phone: '452-652-5230',
    fax: '452-652-5231',
    email: 'riteaid789@riteaid.com',
    website: 'www.riteaid789.com',
    address: '19103 Stefani Ave, Cerritos, CA, 90703',
    businessHours: '8 AM - 9 PM',
    licenseNumber: 'PH98765',
    licenseExpiration: '2027-01-05',
    npiNumber: '7654321098',
    insuranceAccepted: ['Kaiser Permanente', 'Medicare', 'Aetna'],
    servicesOffered: ['Vaccinations', 'Compounding', 'Prescription Refill Reminders'],
    pharmacyChain: 'Rite Aid',
    managerName: 'Emily Davis',
    frequentlycontacted: false,
    starred: true,
    deleted: true,
    pharmacists: [206],
    requests: [101, 102],
  },
  {
    id: 5,
    pharmacyName: 'HealthFirst Specialty Pharmacy',
    pharmacyType: 'Compounding',
    phone: '985-985-7850',
    fax: '985-985-7851',
    email: 'info@healthfirstspecialty.com',
    website: 'www.healthfirstspecialty.com',
    address: '3059 Edgewood Park Ct, Commerce Township, MI',
    businessHours: '9 AM - 5 PM',
    licenseNumber: 'PH65432',
    licenseExpiration: '2026-11-19',
    npiNumber: '6543210987',
    insuranceAccepted: ['BlueCross BlueShield', 'Cigna'],
    servicesOffered: ['Sterile Compounding', 'Hormone Replacement Therapy'],
    pharmacyChain: 'Independent',
    managerName: 'Sophia Lopez',
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacists: [207, 208],
    requests: [101, 102],
  },
  {
    id: 6,
    pharmacyName: 'Wellness Pharmacy',
    pharmacyType: 'Independent',
    phone: '456-789-1234',
    fax: '456-789-4321',
    email: 'contact@wellnesspharmacy.com',
    website: 'www.wellnesspharmacy.com',
    address: '5023 Maple St, Springfield, IL',
    businessHours: '8 AM - 6 PM',
    licenseNumber: 'PH87643',
    licenseExpiration: '2025-12-12',
    npiNumber: '8765432190',
    insuranceAccepted: ['Aetna', 'Cigna', 'Medicaid'],
    servicesOffered: ['Vaccinations', 'Medication Therapy Management', 'Delivery'],
    pharmacyChain: 'Independent',
    managerName: 'James Taylor',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacists: [209],
    requests: [101, 102],
  },
  {
    id: 7,
    pharmacyName: 'Happy Health Pharmacy',
    pharmacyType: 'Retail',
    phone: '321-654-9870',
    fax: '321-654-9871',
    email: 'info@happyhealth.com',
    website: 'www.happyhealth.com',
    address: '1109 Cedar Rd, Kansas City, MO',
    businessHours: '9 AM - 7 PM',
    licenseNumber: 'PH54321',
    licenseExpiration: '2024-09-15',
    npiNumber: '7654321098',
    insuranceAccepted: ['BlueCross BlueShield', 'Medicare', 'Humana'],
    servicesOffered: ['Compounding', 'Vaccinations', 'Prescription Delivery'],
    pharmacyChain: 'Independent',
    managerName: 'Laura White',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacists: [210, 211],
    requests: [101, 102],
  },
  {
    id: 8,
    pharmacyName: 'LifeCare Pharmacy',
    pharmacyType: 'Hospital Pharmacy',
    phone: '212-654-7890',
    fax: '212-654-7891',
    email: 'lcare@lifecarepharmacy.com',
    website: 'www.lifecarepharmacy.com',
    address: '8903 Oak St, New York, NY',
    businessHours: 'Open 24 hours',
    licenseNumber: 'PH65478',
    licenseExpiration: '2026-05-28',
    npiNumber: '9876543210',
    insuranceAccepted: ['Aetna', 'Kaiser Permanente', 'Medicare'],
    servicesOffered: ['Inpatient Services', 'Emergency Medications', 'Clinical Support'],
    pharmacyChain: 'LifeCare Health',
    managerName: 'Eleanor Davis',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacists: [212],
    requests: [101, 102],
  },
  {
    id: 9,
    pharmacyName: 'MedStar Pharmacy',
    pharmacyType: 'Hospital Pharmacy',
    phone: '202-654-0987',
    fax: '202-654-9876',
    email: 'medstar@medstar.com',
    website: 'www.medstarpharmacy.com',
    address: '1458 Monroe St NW, Washington, DC',
    businessHours: '7 AM - 8 PM',
    licenseNumber: 'PH23489',
    licenseExpiration: '2024-12-01',
    npiNumber: '2345678901',
    insuranceAccepted: ['BlueCross BlueShield', 'Humana', 'United Healthcare'],
    servicesOffered: ['Inpatient Services', 'Specialty Medications'],
    pharmacyChain: 'MedStar Health',
    managerName: 'John Clarkson',
    frequentlycontacted: false,
    starred: false,
    deleted: true,
    pharmacists: [213],
    requests: [101, 102],
  },
  {
    id: 10,
    pharmacyName: 'Grand Rx',
    pharmacyType: 'Independent',
    phone: '987-321-6543',
    fax: '987-321-6542',
    email: 'contact@grandrx.com',
    website: 'www.grandrx.com',
    address: '3207 Birch Ln, San Diego, CA',
    businessHours: '8 AM - 6 PM',
    licenseNumber: 'PH34876',
    licenseExpiration: '2025-10-20',
    npiNumber: '1098765432',
    insuranceAccepted: ['Medicaid', 'Medicare', 'Cigna'],
    servicesOffered: ['Prescription Refill', 'Vaccinations', 'Clinical Services'],
    pharmacyChain: 'Independent',
    managerName: 'Linda Roberts',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacists: [214, 215],
    requests: [101, 102],
  },
  {
    id: 11,
    pharmacyName: 'Peak Wellness Pharmacy',
    pharmacyType: 'Retail',
    phone: '654-987-1234',
    fax: '654-987-1235',
    email: 'info@peakwellness.com',
    website: 'www.peakwellness.com',
    address: '7843 Hilltop Rd, Boulder, CO',
    businessHours: '9 AM - 8 PM',
    licenseNumber: 'PH98765',
    licenseExpiration: '2026-07-17',
    npiNumber: '8765432109',
    insuranceAccepted: ['United Healthcare', 'Aetna', 'Humana'],
    servicesOffered: ['Vaccinations', 'Compounding', 'Prescription Synchronization'],
    pharmacyChain: 'Peak Wellness Group',
    managerName: 'Thomas Watson',
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacists: [216, 217],
    requests: [101, 102],
  },
  {
    id: 12,
    pharmacyName: 'Healthway Pharmacy',
    pharmacyType: 'Independent',
    phone: '789-654-3210',
    fax: '789-654-3211',
    email: 'support@healthway.com',
    website: 'www.healthwaypharmacy.com',
    address: '1200 Elm St, Seattle, WA',
    businessHours: '8 AM - 7 PM',
    licenseNumber: 'PH54387',
    licenseExpiration: '2027-02-01',
    npiNumber: '1234567890',
    insuranceAccepted: ['Medicare', 'Cigna', 'BlueCross BlueShield'],
    servicesOffered: ['Compounding', 'Vaccinations', 'Prescription Delivery'],
    pharmacyChain: 'Independent',
    managerName: 'Anna Green',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacists: [218],
    requests: [101, 102],
  },
  {
    id: 13,
    pharmacyName: 'WellCare Pharmacy',
    pharmacyType: 'Retail',
    phone: '654-123-7890',
    fax: '654-123-7891',
    email: 'wellcare@wellcarepharmacy.com',
    website: 'www.wellcarepharmacy.com',
    address: '6345 Pine St, Orlando, FL',
    businessHours: '9 AM - 9 PM',
    licenseNumber: 'PH76345',
    licenseExpiration: '2025-11-10',
    npiNumber: '9876543210',
    insuranceAccepted: ['Aetna', 'Medicare', 'Humana'],
    servicesOffered: ['Clinical Consultations', 'Prescription Synchronization'],
    pharmacyChain: 'WellCare Health',
    managerName: 'Oliver King',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacists: [219, 220],
    requests: [101, 102],
  },
  {
    id: 14,
    pharmacyName: 'MainStreet Rx',
    pharmacyType: 'Independent',
    phone: '890-123-4567',
    fax: '890-123-7654',
    email: 'info@mainstreetrx.com',
    website: 'www.mainstreetrx.com',
    address: '320 Main St, Franklin, TN',
    businessHours: '9 AM - 6 PM',
    licenseNumber: 'PH98765',
    licenseExpiration: '2024-06-30',
    npiNumber: '6543210987',
    insuranceAccepted: ['Medicaid', 'Aetna', 'United Healthcare'],
    servicesOffered: ['Prescription Refill', 'Vaccinations'],
    pharmacyChain: 'Independent',
    managerName: 'Emma Scott',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacists: [221],
    requests: [101, 102],
  },
  {
    id: 15,
    pharmacyName: 'CareMax Pharmacy',
    pharmacyType: 'Hospital Pharmacy',
    phone: '987-654-3210',
    fax: '987-654-3211',
    email: 'contact@caremaxpharmacy.com',
    website: 'www.caremaxpharmacy.com',
    address: '8903 Hill St, Miami, FL',
    businessHours: 'Open 24 hours',
    licenseNumber: 'PH98760',
    licenseExpiration: '2026-09-15',
    npiNumber: '8765432109',
    insuranceAccepted: ['Medicare', 'Cigna', 'Kaiser Permanente'],
    servicesOffered: ['Inpatient Services', 'Clinical Consultations'],
    pharmacyChain: 'CareMax Health',
    managerName: 'Sophia Lee',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacists: [222, 223],
    requests: [101, 102],
  },
  {
    id: 16,
    pharmacyName: 'Oakwood Pharmacy',
    pharmacyType: 'Compounding',
    phone: '123-456-7890',
    fax: '123-456-7891',
    email: 'info@oakwoodpharmacy.com',
    website: 'www.oakwoodpharmacy.com',
    address: '110 Maple St, Phoenix, AZ',
    businessHours: '8 AM - 5 PM',
    licenseNumber: 'PH98764',
    licenseExpiration: '2026-11-22',
    npiNumber: '5678901234',
    insuranceAccepted: ['Humana', 'Medicare', 'Cigna'],
    servicesOffered: ['Sterile Compounding', 'Hormone Replacement Therapy'],
    pharmacyChain: 'Independent',
    managerName: 'Sophia Lopez',
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacists: [224],
    requests: [101, 102],
  },
  {
    id: 17,
    pharmacyName: 'Sunshine Health Pharmacy',
    pharmacyType: 'Retail',
    phone: '789-456-1230',
    fax: '789-456-1231',
    email: 'contact@sunshinehealth.com',
    website: 'www.sunshinehealthpharmacy.com',
    address: '5632 Sunshine Blvd, Tampa, FL',
    businessHours: '9 AM - 8 PM',
    licenseNumber: 'PH12345',
    licenseExpiration: '2025-03-11',
    npiNumber: '6547893210',
    insuranceAccepted: ['Aetna', 'BlueCross BlueShield', 'Humana'],
    servicesOffered: ['Vaccinations', 'Prescription Refill', 'Home Delivery'],
    pharmacyChain: 'Independent',
    managerName: 'Lucas Johnson',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacists: [225, 226],
    requests: [101, 102],
  },
  {
    id: 18,
    pharmacyName: 'RiverView Pharmacy',
    pharmacyType: 'Retail',
    phone: '654-321-7890',
    fax: '654-321-7891',
    email: 'support@riverviewpharmacy.com',
    website: 'www.riverviewpharmacy.com',
    address: '213 River Dr, Cincinnati, OH',
    businessHours: '8 AM - 6 PM',
    licenseNumber: 'PH34567',
    licenseExpiration: '2027-07-15',
    npiNumber: '1234569870',
    insuranceAccepted: ['Medicare', 'Medicaid', 'Cigna'],
    servicesOffered: ['Clinical Consultations', 'Prescription Refill', 'Vaccinations'],
    pharmacyChain: 'RiverView Health',
    managerName: 'Oliver Baker',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacists: [227],
    requests: [101, 102],
  },
  {
    id: 19,
    pharmacyName: 'Pinnacle Pharmacy',
    pharmacyType: 'Hospital Pharmacy',
    phone: '987-654-3212',
    fax: '987-654-3213',
    email: 'info@pinnaclepharmacy.com',
    website: 'www.pinnaclepharmacy.com',
    address: '4302 Pinnacle Way, Chicago, IL',
    businessHours: '7 AM - 7 PM',
    licenseNumber: 'PH87654',
    licenseExpiration: '2026-02-08',
    npiNumber: '7890123456',
    insuranceAccepted: ['Aetna', 'United Healthcare', 'Kaiser Permanente'],
    servicesOffered: ['Inpatient Services', 'Specialty Medications', 'Vaccinations'],
    pharmacyChain: 'Pinnacle Health',
    managerName: 'Grace Mitchell',
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacists: [228, 229],
    requests: [101, 102],
  },
  {
    id: 20,
    pharmacyName: 'CarePoint Pharmacy',
    pharmacyType: 'Independent',
    phone: '321-654-9873',
    fax: '321-654-9874',
    email: 'support@carepointpharmacy.com',
    website: 'www.carepointpharmacy.com',
    address: '1123 Oak Ridge Dr, Los Angeles, CA',
    businessHours: '9 AM - 7 PM',
    licenseNumber: 'PH43210',
    licenseExpiration: '2025-06-22',
    npiNumber: '4567890123',
    insuranceAccepted: ['Medicare', 'Cigna', 'Aetna'],
    servicesOffered: ['Compounding', 'Prescription Delivery', 'Vaccinations'],
    pharmacyChain: 'Independent',
    managerName: 'Henry White',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacists: [230],
    requests: [101, 102],
  },
  {
    id: 21,
    pharmacyName: 'PrimeCare Pharmacy',
    pharmacyType: 'Retail',
    phone: '654-321-0987',
    fax: '654-321-0986',
    email: 'info@primecarepharmacy.com',
    website: 'www.primecarepharmacy.com',
    address: '1020 Elm St, Dallas, TX',
    businessHours: '8 AM - 8 PM',
    licenseNumber: 'PH56789',
    licenseExpiration: '2026-09-30',
    npiNumber: '8765432101',
    insuranceAccepted: ['Medicaid', 'Humana', 'United Healthcare'],
    servicesOffered: ['Vaccinations', 'Prescription Refill', 'Health Screenings'],
    pharmacyChain: 'PrimeCare Health',
    managerName: 'Olivia Bennett',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacists: [231, 232],
    requests: [101, 102],
  },
  {
    id: 22,
    pharmacyName: 'Cornerstone Pharmacy',
    pharmacyType: 'Compounding',
    phone: '987-321-4567',
    fax: '987-321-4568',
    email: 'contact@cornerstonepharmacy.com',
    website: 'www.cornerstonepharmacy.com',
    address: '2301 Hilltop Ave, Denver, CO',
    businessHours: '9 AM - 5 PM',
    licenseNumber: 'PH09876',
    licenseExpiration: '2025-04-18',
    npiNumber: '2345678901',
    insuranceAccepted: ['Cigna', 'Aetna', 'Medicare'],
    servicesOffered: ['Compounding', 'Hormone Replacement Therapy', 'Vaccinations'],
    pharmacyChain: 'Cornerstone Health',
    managerName: 'Ethan Reed',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacists: [233],
    requests: [101, 102],
  },
  {
    id: 23,
    pharmacyName: 'Essential Rx',
    pharmacyType: 'Retail',
    phone: '789-654-1234',
    fax: '789-654-1235',
    email: 'support@essentialrx.com',
    website: 'www.essentialrx.com',
    address: '7890 Oak St, San Francisco, CA',
    businessHours: '8 AM - 6 PM',
    licenseNumber: 'PH76543',
    licenseExpiration: '2027-01-12',
    npiNumber: '5432109876',
    insuranceAccepted: ['Humana', 'BlueCross BlueShield', 'Medicare'],
    servicesOffered: ['Prescription Delivery', 'Vaccinations', 'Consultations'],
    pharmacyChain: 'Essential Health',
    managerName: 'Isabella Taylor',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacists: [234, 235],
    requests: [101, 102],
  },
  {
    id: 24,
    pharmacyName: 'MetroHealth Pharmacy',
    pharmacyType: 'Hospital Pharmacy',
    phone: '456-789-6543',
    fax: '456-789-6542',
    email: 'info@metrohealthpharmacy.com',
    website: 'www.metrohealthpharmacy.com',
    address: '6541 Central Ave, Cleveland, OH',
    businessHours: 'Open 24 hours',
    licenseNumber: 'PH65432',
    licenseExpiration: '2026-03-29',
    npiNumber: '3456789012',
    insuranceAccepted: ['Aetna', 'Cigna', 'Medicaid'],
    servicesOffered: ['Inpatient Services', 'Emergency Medications', 'Clinical Support'],
    pharmacyChain: 'MetroHealth',
    managerName: 'Emily Harris',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacists: [236],
    requests: [101, 102],
  },
  {
    id: 25,
    pharmacyName: 'FamilyFirst Pharmacy',
    pharmacyType: 'Independent',
    phone: '123-789-6541',
    fax: '123-789-6542',
    email: 'contact@familyfirstpharmacy.com',
    website: 'www.familyfirstpharmacy.com',
    address: '9025 Pine Dr, Orlando, FL',
    businessHours: '9 AM - 7 PM',
    licenseNumber: 'PH78965',
    licenseExpiration: '2025-12-05',
    npiNumber: '1234567891',
    insuranceAccepted: ['Medicare', 'Humana', 'Cigna'],
    servicesOffered: ['Vaccinations', 'Prescription Delivery', 'Compounding'],
    pharmacyChain: 'Independent',
    managerName: 'David Clark',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacists: [237, 238],
    requests: [101, 102],
  },
  {
    id: 26,
    pharmacyName: 'UnityRx Pharmacy',
    pharmacyType: 'Retail',
    phone: '654-987-3214',
    fax: '654-987-3215',
    email: 'support@unityrxpharmacy.com',
    website: 'www.unityrxpharmacy.com',
    address: '6712 Maple Ave, Portland, OR',
    businessHours: '8 AM - 9 PM',
    licenseNumber: 'PH43278',
    licenseExpiration: '2026-10-19',
    npiNumber: '9876543219',
    insuranceAccepted: ['Aetna', 'Medicaid', 'Medicare'],
    servicesOffered: ['Vaccinations', 'Health Screenings', 'Prescription Refill'],
    pharmacyChain: 'Unity Health',
    managerName: 'Liam Davis',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacists: [239],
    requests: [101, 102],
  },
  {
    id: 27,
    pharmacyName: 'Health Solutions Pharmacy',
    pharmacyType: 'Hospital Pharmacy',
    phone: '321-456-7890',
    fax: '321-456-7891',
    email: 'info@healthsolutionspharmacy.com',
    website: 'www.healthsolutionspharmacy.com',
    address: '1234 Health St, Atlanta, GA',
    businessHours: 'Open 24 hours',
    licenseNumber: 'PH65498',
    licenseExpiration: '2027-02-16',
    npiNumber: '2345678910',
    insuranceAccepted: ['Cigna', 'Humana', 'United Healthcare'],
    servicesOffered: ['Inpatient Services', 'Clinical Consultations', 'Specialty Medications'],
    pharmacyChain: 'Health Solutions',
    managerName: 'Mia Johnson',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacists: [240, 241],
    requests: [101, 102],
  },
  {
    id: 28,
    pharmacyName: 'AccessCare Pharmacy',
    pharmacyType: 'Compounding',
    phone: '654-789-3214',
    fax: '654-789-3215',
    email: 'support@accesscarepharmacy.com',
    website: 'www.accesscarepharmacy.com',
    address: '9803 Birch St, Sacramento, CA',
    businessHours: '9 AM - 5 PM',
    licenseNumber: 'PH54321',
    licenseExpiration: '2025-11-02',
    npiNumber: '3456789011',
    insuranceAccepted: ['Aetna', 'Medicare', 'Cigna'],
    servicesOffered: ['Compounding', 'Prescription Delivery', 'Vaccinations'],
    pharmacyChain: 'AccessCare',
    managerName: 'Charlotte Wilson',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacists: [242],
    requests: [101, 102],
  },
  {
    id: 29,
    pharmacyName: 'BrightView Pharmacy',
    pharmacyType: 'Retail',
    phone: '789-654-1234',
    fax: '789-654-1235',
    email: 'info@brightviewpharmacy.com',
    website: 'www.brightviewpharmacy.com',
    address: '7682 Willow Ave, Las Vegas, NV',
    businessHours: '9 AM - 8 PM',
    licenseNumber: 'PH87654',
    licenseExpiration: '2026-04-14',
    npiNumber: '5678901234',
    insuranceAccepted: ['Medicaid', 'Cigna', 'Aetna'],
    servicesOffered: ['Vaccinations', 'Prescription Refill', 'Home Delivery'],
    pharmacyChain: 'Independent',
    managerName: 'Sophia Brown',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacists: [243, 244],
    requests: [101, 102],
  },
  {
    id: 30,
    pharmacyName: 'Neighborhood Wellness Pharmacy',
    pharmacyType: 'Retail',
    phone: '456-321-7890',
    fax: '456-321-7891',
    email: 'contact@neighborhoodwellness.com',
    website: 'www.neighborhoodwellness.com',
    address: '3210 Lakeview St, Salt Lake City, UT',
    businessHours: '9 AM - 7 PM',
    licenseNumber: 'PH12398',
    licenseExpiration: '2027-08-21',
    npiNumber: '8765432190',
    insuranceAccepted: ['Aetna', 'Humana', 'Medicare'],
    servicesOffered: ['Vaccinations', 'Prescription Delivery', 'Health Screenings'],
    pharmacyChain: 'Neighborhood Wellness',
    managerName: 'Amelia Morgan',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacists: [245],
    requests: [101, 102],
  }
];
mock.onGet('/api/data/pharmacies/PharmaciesData').reply(() => {
  const pharmacies = PharmacyList;
  return [200, JSON.parse(JSON.stringify(pharmacies))];
});
export default PharmacyList;
