import mock from '../mock';
import user1 from 'src/assets/images/profile/user-1.jpg';
import user2 from 'src/assets/images/profile/user-2.jpg';
import user3 from 'src/assets/images/profile/user-3.jpg';
import user4 from 'src/assets/images/profile/user-4.jpg';
import user5 from 'src/assets/images/profile/user-5.jpg';

const ItemData = [
    {
        "Id": 1,
        "GenericName": "Acetaminophen",
        "BrandName": "Tylenol",
        "Class": "Analgesic",
        "Use": "Pain relief, fever",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC",
        "Dosage": "500 mg, PRN",
        "SideEffects": "Nausea, rash",
        "PregnancyCategory": "B",
        "Label": "otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 2,
        "GenericName": "Adalimumab",
        "BrandName": "Humira",
        "Class": "Biologic (Anti-TNF)",
        "Use": "Rheumatoid arthritis",
        "DeliveryMechanism": "Injection",
        "Schedule": "Rx",
        "Dosage": "40 mg SC",
        "SideEffects": "Injection site reactions",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 3,
        "GenericName": "Albuterol",
        "BrandName": "Ventolin, ProAir",
        "Class": "Bronchodilator",
        "Use": "Asthma, COPD",
        "DeliveryMechanism": "Inhaler",
        "Schedule": "Rx",
        "Dosage": "PRN for SOB",
        "SideEffects": "Tremor, increased HR",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 4,
        "GenericName": "Alprazolam",
        "BrandName": "Xanax",
        "Class": "Benzodiazepine",
        "Use": "Anxiety disorders",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule IV",
        "Dosage": "0.25-0.5 mg",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "D",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 5,
        "GenericName": "Amlodipine",
        "BrandName": "Norvasc",
        "Class": "Calcium channel blocker",
        "Use": "Hypertension",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-10 mg daily",
        "SideEffects": "Swelling, dizziness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 6,
        "GenericName": "Amoxicillin",
        "BrandName": "Amoxil",
        "Class": "Antibiotic",
        "Use": "Bacterial infections",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "500 mg BID",
        "SideEffects": "GI upset, rash",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 7,
        "GenericName": "Atorvastatin",
        "BrandName": "Lipitor",
        "Class": "Statin",
        "Use": "Cholesterol reduction",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-80 mg daily",
        "SideEffects": "Muscle pain, headache",
        "PregnancyCategory": "X (not for pregnancy)",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 8,
        "GenericName": "Amphetamine/Dextroamphetamine",
        "BrandName": "Adderall",
        "Class": "CNS Stimulant",
        "Use": "ADHD, Narcolepsy",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule II",
        "Dosage": "10-30 mg daily",
        "SideEffects": "Insomnia, weight loss",
        "PregnancyCategory": "C",
        "Label": "schedule-ii",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 9,
        "GenericName": "Anastrozole",
        "BrandName": "Arimidex",
        "Class": "Aromatase Inhibitor",
        "Use": "Breast cancer treatment",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "1 mg daily",
        "SideEffects": "Hot flashes, joint pain",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 10,
        "GenericName": "Apixaban",
        "BrandName": "Eliquis",
        "Class": "Anticoagulant",
        "Use": "Stroke prevention, blood clot treatment",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5 mg BID",
        "SideEffects": "Bleeding, nausea",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 11,
        "GenericName": "Atenolol",
        "BrandName": "Tenormin",
        "Class": "Beta-blocker",
        "Use": "Hypertension, angina",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "25-100 mg daily",
        "SideEffects": "Fatigue, dizziness",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 12,
        "GenericName": "Atomoxetine",
        "BrandName": "Strattera",
        "Class": "Selective Norepinephrine Reuptake Inhibitor (NRI)",
        "Use": "ADHD",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "40-100 mg daily",
        "SideEffects": "Dry mouth, appetite suppression",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 13,
        "GenericName": "Atropine",
        "BrandName": "AtroPen, Isopto Atropine",
        "Class": "Anticholinergic",
        "Use": "Bradycardia, organophosphate poisoning",
        "DeliveryMechanism": "Injection, Ophthalmic",
        "Schedule": "Rx",
        "Dosage": "Based on condition",
        "SideEffects": "Dry mouth, blurred vision",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 14,
        "GenericName": "Avanafil",
        "BrandName": "Stendra",
        "Class": "PDE5 Inhibitor",
        "Use": "Erectile dysfunction",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "50-200 mg PRN",
        "SideEffects": "Headache, flushing",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 15,
        "GenericName": "Azithromycin",
        "BrandName": "Zithromax, Z-Pak",
        "Class": "Macrolide Antibiotic",
        "Use": "Bacterial infections",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "500 mg day 1, 250 mg days 2-5",
        "SideEffects": "Diarrhea, nausea, abdominal pain",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 16,
        "GenericName": "Baclofen",
        "BrandName": "Lioresal",
        "Class": "Muscle Relaxant",
        "Use": "Muscle spasms, spasticity",
        "DeliveryMechanism": "Oral, Intrathecal",
        "Schedule": "Rx",
        "Dosage": "5-20 mg 3x daily",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 17,
        "GenericName": "Benazepril",
        "BrandName": "Lotensin",
        "Class": "ACE Inhibitor",
        "Use": "Hypertension",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-40 mg daily",
        "SideEffects": "Cough, dizziness, headache",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 18,
        "GenericName": "Benzonatate",
        "BrandName": "Tessalon Perles",
        "Class": "Antitussive",
        "Use": "Cough",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "100-200 mg TID PRN",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 19,
        "GenericName": "Betamethasone",
        "BrandName": "Celestone, Diprolene",
        "Class": "Corticosteroid",
        "Use": "Inflammation, allergic reactions",
        "DeliveryMechanism": "Oral, Topical, Injection",
        "Schedule": "Rx",
        "Dosage": "0.6-7.2 mg daily",
        "SideEffects": "Weight gain, fluid retention",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 20,
        "GenericName": "Bimatoprost",
        "BrandName": "Lumigan, Latisse",
        "Class": "Prostaglandin Analog",
        "Use": "Glaucoma, eyelash growth",
        "DeliveryMechanism": "Ophthalmic",
        "Schedule": "Rx",
        "Dosage": "1 drop once daily",
        "SideEffects": "Eye irritation, redness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 21,
        "GenericName": "Bisoprolol",
        "BrandName": "Zebeta",
        "Class": "Beta-blocker",
        "Use": "Hypertension",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-10 mg daily",
        "SideEffects": "Fatigue, bradycardia",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 22,
        "GenericName": "Brimonidine",
        "BrandName": "Alphagan P",
        "Class": "Alpha Agonist",
        "Use": "Glaucoma",
        "DeliveryMechanism": "Ophthalmic",
        "Schedule": "Rx",
        "Dosage": "1 drop 2-3x daily",
        "SideEffects": "Eye irritation, dry mouth",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 23,
        "GenericName": "Budesonide",
        "BrandName": "Pulmicort, Rhinocort",
        "Class": "Corticosteroid",
        "Use": "Asthma, allergic rhinitis",
        "DeliveryMechanism": "Inhaler, Nasal Spray",
        "Schedule": "Rx",
        "Dosage": "Inhalation 180-720 mcg/day",
        "SideEffects": "Oral thrush, cough, hoarseness",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 24,
        "GenericName": "Buprenorphine",
        "BrandName": "Subutex, Belbuca",
        "Class": "Partial Opioid Agonist/Antagonist",
        "Use": "Opioid dependence, pain management",
        "DeliveryMechanism": "Sublingual, Patch",
        "Schedule": "Schedule III",
        "Dosage": "2-16 mg daily",
        "SideEffects": "Constipation, nausea",
        "PregnancyCategory": "C (used with caution)",
        "Label": "schedule-iii",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 25,
        "GenericName": "Bupropion",
        "BrandName": "Wellbutrin, Zyban",
        "Class": "Antidepressant",
        "Use": "Depression, smoking cessation",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "150-300 mg daily",
        "SideEffects": "Insomnia, dry mouth",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 26,
        "GenericName": "Buspirone",
        "BrandName": "Buspar",
        "Class": "Anxiolytic",
        "Use": "Anxiety disorders",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "15-30 mg daily",
        "SideEffects": "Dizziness, nausea",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 27,
        "GenericName": "Canagliflozin",
        "BrandName": "Invokana",
        "Class": "SGLT2 Inhibitor",
        "Use": "Type 2 Diabetes",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "100-300 mg daily",
        "SideEffects": "Urinary tract infections, dehydration",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 28,
        "GenericName": "Carvedilol",
        "BrandName": "Coreg",
        "Class": "Beta-blocker",
        "Use": "Hypertension, heart failure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "3.125-50 mg BID",
        "SideEffects": "Dizziness, fatigue",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 29,
        "GenericName": "Cefdinir",
        "BrandName": "Omnicef",
        "Class": "Cephalosporin Antibiotic",
        "Use": "Bacterial infections",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "300 mg BID for 10 days",
        "SideEffects": "Diarrhea, nausea",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 30,
        "GenericName": "Cephalexin",
        "BrandName": "Keflex",
        "Class": "Cephalosporin Antibiotic",
        "Use": "Bacterial infections",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "500 mg QID for 7-14 days",
        "SideEffects": "Diarrhea, rash",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 31,
        "GenericName": "Cetirizine",
        "BrandName": "Zyrtec",
        "Class": "Antihistamine",
        "Use": "Allergic rhinitis, hives",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC",
        "Dosage": "5-10 mg daily",
        "SideEffects": "Drowsiness, dry mouth",
        "PregnancyCategory": "B",
        "Label": "otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 32,
        "GenericName": "Chlorthalidone",
        "BrandName": "Thalitone",
        "Class": "Thiazide Diuretic",
        "Use": "Hypertension, edema",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "12.5-25 mg daily",
        "SideEffects": "Dizziness, dehydration",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 33,
        "GenericName": "Citalopram",
        "BrandName": "Celexa",
        "Class": "SSRI",
        "Use": "Depression, anxiety disorders",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "20-40 mg daily",
        "SideEffects": "Insomnia, sexual dysfunction",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 34,
        "GenericName": "Clindamycin",
        "BrandName": "Cleocin",
        "Class": "Lincosamide Antibiotic",
        "Use": "Bacterial infections",
        "DeliveryMechanism": "Oral, IV, Topical",
        "Schedule": "Rx",
        "Dosage": "150-450 mg every 6 hours",
        "SideEffects": "Diarrhea, nausea",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 35,
        "GenericName": "Clonazepam",
        "BrandName": "Klonopin",
        "Class": "Benzodiazepine",
        "Use": "Anxiety disorders, seizures",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule IV",
        "Dosage": "0.25-2 mg daily",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "D",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 36,
        "GenericName": "Clonidine",
        "BrandName": "Catapres",
        "Class": "Alpha-2 Agonist",
        "Use": "Hypertension, ADHD",
        "DeliveryMechanism": "Oral, Patch",
        "Schedule": "Rx",
        "Dosage": "0.1-0.3 mg BID",
        "SideEffects": "Drowsiness, dry mouth",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 37,
        "GenericName": "Clopidogrel",
        "BrandName": "Plavix",
        "Class": "Antiplatelet",
        "Use": "Stroke, heart attack prevention",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "75 mg daily",
        "SideEffects": "Bleeding, bruising",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 38,
        "GenericName": "Cyclobenzaprine",
        "BrandName": "Flexeril",
        "Class": "Muscle Relaxant",
        "Use": "Muscle spasms",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-10 mg TID",
        "SideEffects": "Drowsiness, dry mouth",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 39,
        "GenericName": "Dapagliflozin",
        "BrandName": "Farxiga",
        "Class": "SGLT2 Inhibitor",
        "Use": "Type 2 Diabetes, heart failure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-10 mg daily",
        "SideEffects": "Urinary tract infections, dehydration",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 40,
        "GenericName": "Diazepam",
        "BrandName": "Valium",
        "Class": "Benzodiazepine",
        "Use": "Anxiety, muscle spasms, seizures",
        "DeliveryMechanism": "Oral, IV, Rectal",
        "Schedule": "Schedule IV",
        "Dosage": "2-10 mg TID",
        "SideEffects": "Drowsiness, muscle weakness",
        "PregnancyCategory": "D",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 41,
        "GenericName": "Diclofenac",
        "BrandName": "Voltaren, Cataflam",
        "Class": "NSAID",
        "Use": "Pain, inflammation",
        "DeliveryMechanism": "Oral, Topical",
        "Schedule": "Rx/OTC",
        "Dosage": "50 mg BID/TID (oral), Topical as directed",
        "SideEffects": "Stomach pain, rash",
        "PregnancyCategory": "C",
        "Label": "rx/otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 42,
        "GenericName": "Diltiazem",
        "BrandName": "Cardizem, Tiazac",
        "Class": "Calcium Channel Blocker",
        "Use": "Hypertension, angina",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "120-360 mg daily",
        "SideEffects": "Dizziness, edema",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 43,
        "GenericName": "Divalproex",
        "BrandName": "Depakote",
        "Class": "Anticonvulsant, Mood Stabilizer",
        "Use": "Seizures, bipolar disorder, migraines",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "250-500 mg daily",
        "SideEffects": "Nausea, weight gain",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 44,
        "GenericName": "Donepezil",
        "BrandName": "Aricept",
        "Class": "Acetylcholinesterase Inhibitor",
        "Use": "Alzheimer\u2019s disease",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-10 mg daily",
        "SideEffects": "Nausea, insomnia",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 45,
        "GenericName": "Doxazosin",
        "BrandName": "Cardura",
        "Class": "Alpha Blocker",
        "Use": "Hypertension, benign prostatic hyperplasia",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "1-8 mg daily",
        "SideEffects": "Dizziness, fatigue",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 46,
        "GenericName": "Doxycycline",
        "BrandName": "Vibramycin, Doryx",
        "Class": "Tetracycline Antibiotic",
        "Use": "Bacterial infections",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "100 mg BID",
        "SideEffects": "Nausea, photosensitivity",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 47,
        "GenericName": "Duloxetine",
        "BrandName": "Cymbalta",
        "Class": "SNRI",
        "Use": "Depression, anxiety, fibromyalgia",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "30-60 mg daily",
        "SideEffects": "Nausea, fatigue, dry mouth",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 48,
        "GenericName": "Empagliflozin",
        "BrandName": "Jardiance",
        "Class": "SGLT2 Inhibitor",
        "Use": "Type 2 Diabetes, heart failure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-25 mg daily",
        "SideEffects": "Urinary tract infections, dehydration",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 49,
        "GenericName": "Enalapril",
        "BrandName": "Vasotec",
        "Class": "ACE Inhibitor",
        "Use": "Hypertension, heart failure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "2.5-40 mg daily",
        "SideEffects": "Dizziness, cough",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 50,
        "GenericName": "Escitalopram",
        "BrandName": "Lexapro",
        "Class": "SSRI",
        "Use": "Depression, anxiety disorders",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-20 mg daily",
        "SideEffects": "Nausea, insomnia, sexual dysfunction",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 51,
        "GenericName": "Esomeprazole",
        "BrandName": "Nexium",
        "Class": "Proton Pump Inhibitor",
        "Use": "GERD, acid reflux",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx/OTC",
        "Dosage": "20-40 mg daily",
        "SideEffects": "Headache, abdominal pain",
        "PregnancyCategory": "B",
        "Label": "rx/otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 52,
        "GenericName": "Ezetimibe",
        "BrandName": "Zetia",
        "Class": "Cholesterol Absorption Inhibitor",
        "Use": "High cholesterol",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10 mg daily",
        "SideEffects": "Diarrhea, muscle pain",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 53,
        "GenericName": "Epinephrine (auto-injector)",
        "BrandName": "EpiPen, Auvi-Q",
        "Class": "Adrenergic Agonist",
        "Use": "Anaphylaxis",
        "DeliveryMechanism": "Injection (Auto-Injector)",
        "Schedule": "Rx",
        "Dosage": "0.3 mg per injection PRN",
        "SideEffects": "Anxiety, tremor, increased heart rate",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 54,
        "GenericName": "Edoxaban",
        "BrandName": "Savaysa",
        "Class": "Anticoagulant",
        "Use": "Stroke prevention, blood clots",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "60 mg daily",
        "SideEffects": "Bleeding, rash, liver function changes",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 55,
        "GenericName": "Eszopiclone",
        "BrandName": "Lunesta",
        "Class": "Hypnotic",
        "Use": "Insomnia",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule IV",
        "Dosage": "1-3 mg before bedtime",
        "SideEffects": "Drowsiness, dry mouth, headache",
        "PregnancyCategory": "C",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 56,
        "GenericName": "Famotidine",
        "BrandName": "Pepcid",
        "Class": "H2 Receptor Antagonist",
        "Use": "GERD, acid reflux",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "OTC/Rx",
        "Dosage": "20-40 mg daily",
        "SideEffects": "Headache, constipation",
        "PregnancyCategory": "B",
        "Label": "otc/rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 57,
        "GenericName": "Fenofibrate",
        "BrandName": "Tricor, Lofibra",
        "Class": "Fibrate",
        "Use": "High cholesterol, triglycerides",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "48-145 mg daily",
        "SideEffects": "Abdominal pain, increased liver enzymes",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 58,
        "GenericName": "Fentanyl",
        "BrandName": "Duragesic, Sublimaze",
        "Class": "Opioid Analgesic",
        "Use": "Severe pain",
        "DeliveryMechanism": "Transdermal, Injection, Oral",
        "Schedule": "Schedule II",
        "Dosage": "25-100 mcg/hour patch",
        "SideEffects": "Constipation, respiratory depression",
        "PregnancyCategory": "C",
        "Label": "schedule-ii",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 59,
        "GenericName": "Finasteride",
        "BrandName": "Proscar, Propecia",
        "Class": "5-Alpha Reductase Inhibitor",
        "Use": "Benign prostatic hyperplasia (BPH), hair loss",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "1-5 mg daily",
        "SideEffects": "Decreased libido, erectile dysfunction",
        "PregnancyCategory": "X",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 60,
        "GenericName": "Fluconazole",
        "BrandName": "Diflucan",
        "Class": "Antifungal",
        "Use": "Fungal infections (e.g., yeast infections)",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "150 mg single dose",
        "SideEffects": "Nausea, headache",
        "PregnancyCategory": "D (high doses)",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 61,
        "GenericName": "Fluoxetine",
        "BrandName": "Prozac",
        "Class": "SSRI",
        "Use": "Depression, anxiety, OCD",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "20-80 mg daily",
        "SideEffects": "Insomnia, sexual dysfunction",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 62,
        "GenericName": "Fluticasone (inhaler)",
        "BrandName": "Flovent, Arnuity Ellipta",
        "Class": "Corticosteroid",
        "Use": "Asthma, allergic rhinitis",
        "DeliveryMechanism": "Inhaler, Nasal Spray",
        "Schedule": "Rx",
        "Dosage": "88-440 mcg BID (inhaler)",
        "SideEffects": "Throat irritation, oral thrush",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 63,
        "GenericName": "Furosemide",
        "BrandName": "Lasix",
        "Class": "Loop Diuretic",
        "Use": "Edema, hypertension",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "20-80 mg daily",
        "SideEffects": "Dehydration, electrolyte imbalance",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 64,
        "GenericName": "Fexofenadine",
        "BrandName": "Allegra",
        "Class": "Antihistamine",
        "Use": "Allergic rhinitis, urticaria",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC",
        "Dosage": "60-180 mg daily",
        "SideEffects": "Headache, dry mouth",
        "PregnancyCategory": "C",
        "Label": "otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 65,
        "GenericName": "Fludrocortisone",
        "BrandName": "Florinef",
        "Class": "Corticosteroid",
        "Use": "Addison's disease, low blood pressure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "0.1 mg daily",
        "SideEffects": "Hypertension, swelling",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 66,
        "GenericName": "Flurazepam",
        "BrandName": "Dalmane",
        "Class": "Benzodiazepine",
        "Use": "Insomnia",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule IV",
        "Dosage": "15-30 mg before bedtime",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "C",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 67,
        "GenericName": "Gabapentin",
        "BrandName": "Neurontin",
        "Class": "Anticonvulsant",
        "Use": "Seizures, nerve pain",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "300-600 mg TID",
        "SideEffects": "Dizziness, drowsiness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 68,
        "GenericName": "Glimepiride",
        "BrandName": "Amaryl",
        "Class": "Sulfonylurea",
        "Use": "Type 2 Diabetes",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "1-4 mg daily",
        "SideEffects": "Hypoglycemia, weight gain",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 69,
        "GenericName": "Glipizide",
        "BrandName": "Glucotrol",
        "Class": "Sulfonylurea",
        "Use": "Type 2 Diabetes",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-40 mg daily",
        "SideEffects": "Hypoglycemia, nausea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 70,
        "GenericName": "Glyburide",
        "BrandName": "Diabeta, Micronase",
        "Class": "Sulfonylurea",
        "Use": "Type 2 Diabetes",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "2.5-20 mg daily",
        "SideEffects": "Hypoglycemia, weight gain",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 71,
        "GenericName": "Guaifenesin",
        "BrandName": "Mucinex",
        "Class": "Expectorant",
        "Use": "Cough, chest congestion",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC",
        "Dosage": "200-400 mg every 4 hours",
        "SideEffects": "Nausea, dizziness",
        "PregnancyCategory": "C",
        "Label": "otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 72,
        "GenericName": "Glycopyrrolate",
        "BrandName": "Robinul, Cuvposa",
        "Class": "Anticholinergic",
        "Use": "Peptic ulcers, drooling",
        "DeliveryMechanism": "Oral, Injection",
        "Schedule": "Rx",
        "Dosage": "1-2 mg 2-3x daily",
        "SideEffects": "Dry mouth, constipation",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 73,
        "GenericName": "Haloperidol",
        "BrandName": "Haldol",
        "Class": "Antipsychotic",
        "Use": "Schizophrenia, agitation",
        "DeliveryMechanism": "Oral, Injection",
        "Schedule": "Rx",
        "Dosage": "0.5-5 mg 2-3x daily",
        "SideEffects": "Drowsiness, weight gain",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 74,
        "GenericName": "Hydrochlorothiazide",
        "BrandName": "Microzide",
        "Class": "Thiazide Diuretic",
        "Use": "Hypertension, edema",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "12.5-50 mg daily",
        "SideEffects": "Dizziness, dehydration",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 75,
        "GenericName": "Hydrocodone/Acetaminophen",
        "BrandName": "Norco, Vicodin",
        "Class": "Opioid Analgesic",
        "Use": "Pain relief",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule II",
        "Dosage": "5-10 mg hydrocodone/325-650 mg acetaminophen every 4-6 hours",
        "SideEffects": "Constipation, drowsiness",
        "PregnancyCategory": "C",
        "Label": "schedule-ii",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 76,
        "GenericName": "Hydrocortisone",
        "BrandName": "Cortef, Solu-Cortef",
        "Class": "Corticosteroid",
        "Use": "Inflammation, adrenal insufficiency",
        "DeliveryMechanism": "Oral, Topical, Injection",
        "Schedule": "Rx",
        "Dosage": "20-240 mg daily (oral)",
        "SideEffects": "Weight gain, fluid retention",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 77,
        "GenericName": "Hydroxychloroquine",
        "BrandName": "Plaquenil",
        "Class": "Antimalarial",
        "Use": "Malaria, lupus, rheumatoid arthritis",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "200-400 mg daily",
        "SideEffects": "Nausea, vision problems",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 78,
        "GenericName": "Hyoscyamine",
        "BrandName": "Levsin, Anaspaz",
        "Class": "Anticholinergic",
        "Use": "GI disorders (IBS, cramps)",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "0.125-0.25 mg every 4 hours PRN",
        "SideEffects": "Dry mouth, blurred vision",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 79,
        "GenericName": "Ibuprofen",
        "BrandName": "Advil, Motrin",
        "Class": "NSAID",
        "Use": "Pain, inflammation, fever",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC/Rx",
        "Dosage": "200-800 mg every 6-8 hours",
        "SideEffects": "Nausea, stomach pain",
        "PregnancyCategory": "D (third trimester)",
        "Label": "otc/rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 80,
        "GenericName": "Indapamide",
        "BrandName": "Lozol",
        "Class": "Thiazide-like Diuretic",
        "Use": "Hypertension, edema",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "1.25-2.5 mg daily",
        "SideEffects": "Dizziness, dehydration",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 81,
        "GenericName": "Insulin Aspart",
        "BrandName": "Novolog",
        "Class": "Insulin",
        "Use": "Type 1 & 2 Diabetes",
        "DeliveryMechanism": "Injection",
        "Schedule": "Rx",
        "Dosage": "Individualized based on needs",
        "SideEffects": "Hypoglycemia, weight gain",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 82,
        "GenericName": "Insulin Detemir",
        "BrandName": "Levemir",
        "Class": "Insulin",
        "Use": "Type 1 & 2 Diabetes",
        "DeliveryMechanism": "Injection",
        "Schedule": "Rx",
        "Dosage": "Individualized based on needs",
        "SideEffects": "Hypoglycemia, weight gain",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 83,
        "GenericName": "Insulin Glargine",
        "BrandName": "Lantus, Basaglar",
        "Class": "Insulin",
        "Use": "Type 1 & 2 Diabetes",
        "DeliveryMechanism": "Injection",
        "Schedule": "Rx",
        "Dosage": "Individualized based on needs",
        "SideEffects": "Hypoglycemia, weight gain",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 84,
        "GenericName": "Insulin Lispro",
        "BrandName": "Humalog",
        "Class": "Insulin",
        "Use": "Type 1 & 2 Diabetes",
        "DeliveryMechanism": "Injection",
        "Schedule": "Rx",
        "Dosage": "Individualized based on needs",
        "SideEffects": "Hypoglycemia, weight gain",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 85,
        "GenericName": "Ipratropium (inhaler)",
        "BrandName": "Atrovent",
        "Class": "Anticholinergic",
        "Use": "COPD, asthma",
        "DeliveryMechanism": "Inhaler",
        "Schedule": "Rx",
        "Dosage": "2 puffs QID (17 mcg/puff)",
        "SideEffects": "Dry mouth, cough",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 86,
        "GenericName": "Irbesartan",
        "BrandName": "Avapro",
        "Class": "Angiotensin II Receptor Blocker (ARB)",
        "Use": "Hypertension, diabetic nephropathy",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "150-300 mg daily",
        "SideEffects": "Dizziness, hyperkalemia",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 87,
        "GenericName": "Itraconazole",
        "BrandName": "Sporanox",
        "Class": "Antifungal",
        "Use": "Fungal infections",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "200-400 mg daily",
        "SideEffects": "Nausea, liver enzyme elevation",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 88,
        "GenericName": "Jantoven (Warfarin)**",
        "BrandName": NaN,
        "Class": "Anticoagulant",
        "Use": "Blood clots, stroke prevention",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "Individualized (based on INR)",
        "SideEffects": "Bleeding, bruising",
        "PregnancyCategory": "X",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 89,
        "GenericName": "Jenvoya (Elvitegravir, Cobicistat, Emtricitabine, Tenofovir)**",
        "BrandName": NaN,
        "Class": "Antiretroviral",
        "Use": "HIV infection",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "1 tablet daily",
        "SideEffects": "Nausea, fatigue, diarrhea",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 90,
        "GenericName": "Ketoconazole",
        "BrandName": "Nizoral",
        "Class": "Antifungal",
        "Use": "Fungal infections (e.g., dandruff, athlete's foot)",
        "DeliveryMechanism": "Oral, Topical",
        "Schedule": "Rx/OTC",
        "Dosage": "200 mg daily (oral), Topical as directed",
        "SideEffects": "Nausea, liver toxicity",
        "PregnancyCategory": "C",
        "Label": "rx/otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 91,
        "GenericName": "Ketorolac",
        "BrandName": "Toradol",
        "Class": "NSAID",
        "Use": "Short-term pain relief",
        "DeliveryMechanism": "Oral, Injection",
        "Schedule": "Rx",
        "Dosage": "10 mg every 4-6 hours (max 5 days)",
        "SideEffects": "Stomach pain, nausea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 92,
        "GenericName": "Klor-Con (Potassium Chloride)**",
        "BrandName": NaN,
        "Class": "Electrolyte",
        "Use": "Hypokalemia (low potassium)",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "20-100 mEq daily",
        "SideEffects": "GI discomfort, hyperkalemia",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 93,
        "GenericName": "Lamotrigine",
        "BrandName": "Lamictal",
        "Class": "Anticonvulsant, Mood Stabilizer",
        "Use": "Seizures, bipolar disorder",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "25-200 mg daily",
        "SideEffects": "Rash, dizziness, nausea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 94,
        "GenericName": "Lansoprazole",
        "BrandName": "Prevacid",
        "Class": "Proton Pump Inhibitor",
        "Use": "GERD, acid reflux",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx/OTC",
        "Dosage": "15-30 mg daily",
        "SideEffects": "Headache, abdominal pain",
        "PregnancyCategory": "B",
        "Label": "rx/otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 95,
        "GenericName": "Latanoprost",
        "BrandName": "Xalatan",
        "Class": "Prostaglandin Analog",
        "Use": "Glaucoma",
        "DeliveryMechanism": "Ophthalmic",
        "Schedule": "Rx",
        "Dosage": "1 drop in the affected eye once daily",
        "SideEffects": "Eye irritation, blurry vision",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 96,
        "GenericName": "Levalbuterol",
        "BrandName": "Xopenex",
        "Class": "Bronchodilator",
        "Use": "Asthma, COPD",
        "DeliveryMechanism": "Inhaler",
        "Schedule": "Rx",
        "Dosage": "2 inhalations every 4-6 hours",
        "SideEffects": "Tremor, increased heart rate",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 97,
        "GenericName": "Levetiracetam",
        "BrandName": "Keppra",
        "Class": "Anticonvulsant",
        "Use": "Seizures",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "500-1500 mg BID",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 98,
        "GenericName": "Levofloxacin",
        "BrandName": "Levaquin",
        "Class": "Fluoroquinolone Antibiotic",
        "Use": "Bacterial infections",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "500-750 mg daily",
        "SideEffects": "Nausea, diarrhea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 99,
        "GenericName": "Levothyroxine",
        "BrandName": "Synthroid, Levoxyl",
        "Class": "Thyroid Hormone",
        "Use": "Hypothyroidism",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "25-200 mcg daily",
        "SideEffects": "Palpitations, weight loss",
        "PregnancyCategory": "A",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 100,
        "GenericName": "Liraglutide",
        "BrandName": "Victoza",
        "Class": "GLP-1 Agonist",
        "Use": "Type 2 Diabetes, weight management",
        "DeliveryMechanism": "Injection",
        "Schedule": "Rx",
        "Dosage": "0.6-1.8 mg daily",
        "SideEffects": "Nausea, vomiting, diarrhea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 101,
        "GenericName": "Lisinopril",
        "BrandName": "Zestril, Prinivil",
        "Class": "ACE Inhibitor",
        "Use": "Hypertension, heart failure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-40 mg daily",
        "SideEffects": "Cough, dizziness",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 102,
        "GenericName": "Lithium",
        "BrandName": "Lithobid",
        "Class": "Mood Stabilizer",
        "Use": "Bipolar disorder",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "300-600 mg BID",
        "SideEffects": "Tremor, nausea, increased urination",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 103,
        "GenericName": "Loratadine",
        "BrandName": "Claritin",
        "Class": "Antihistamine",
        "Use": "Allergic rhinitis, hives",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC",
        "Dosage": "10 mg daily",
        "SideEffects": "Drowsiness (rare), dry mouth",
        "PregnancyCategory": "B",
        "Label": "otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 104,
        "GenericName": "Lorazepam",
        "BrandName": "Ativan",
        "Class": "Benzodiazepine",
        "Use": "Anxiety disorders, seizures",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Schedule IV",
        "Dosage": "0.5-2 mg BID/TID",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "D",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 105,
        "GenericName": "Losartan",
        "BrandName": "Cozaar",
        "Class": "Angiotensin II Receptor Blocker (ARB)",
        "Use": "Hypertension, stroke prevention",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "50-100 mg daily",
        "SideEffects": "Dizziness, fatigue",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 106,
        "GenericName": "Lovastatin",
        "BrandName": "Mevacor",
        "Class": "Statin",
        "Use": "High cholesterol",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-40 mg daily",
        "SideEffects": "Muscle pain, liver enzyme elevation",
        "PregnancyCategory": "X",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 107,
        "GenericName": "Lurasidone",
        "BrandName": "Latuda",
        "Class": "Atypical Antipsychotic",
        "Use": "Schizophrenia, bipolar disorder",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "20-120 mg daily",
        "SideEffects": "Weight gain, drowsiness",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 108,
        "GenericName": "Metformin",
        "BrandName": "Glucophage, Fortamet",
        "Class": "Biguanide",
        "Use": "Type 2 Diabetes",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "500-2000 mg daily",
        "SideEffects": "GI upset, nausea, diarrhea",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 109,
        "GenericName": "Methotrexate",
        "BrandName": "Trexall, Rheumatrex",
        "Class": "DMARD (Disease-Modifying Antirheumatic Drug)",
        "Use": "Rheumatoid arthritis, psoriasis, cancer",
        "DeliveryMechanism": "Oral, Injection",
        "Schedule": "Rx",
        "Dosage": "7.5-25 mg weekly",
        "SideEffects": "Nausea, liver toxicity",
        "PregnancyCategory": "X",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 110,
        "GenericName": "Methylprednisolone",
        "BrandName": "Medrol, Solu-Medrol",
        "Class": "Corticosteroid",
        "Use": "Inflammation, allergic conditions",
        "DeliveryMechanism": "Oral, Injection",
        "Schedule": "Rx",
        "Dosage": "4-48 mg daily",
        "SideEffects": "Weight gain, mood changes",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 111,
        "GenericName": "Metoprolol",
        "BrandName": "Lopressor, Toprol XL",
        "Class": "Beta-blocker",
        "Use": "Hypertension, heart failure",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "25-200 mg daily",
        "SideEffects": "Dizziness, fatigue, bradycardia",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 112,
        "GenericName": "Metronidazole",
        "BrandName": "Flagyl",
        "Class": "Antibiotic",
        "Use": "Bacterial infections, parasitic infections",
        "DeliveryMechanism": "Oral, IV, Topical",
        "Schedule": "Rx",
        "Dosage": "500 mg BID for 7-10 days",
        "SideEffects": "Nausea, metallic taste",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 113,
        "GenericName": "Minocycline",
        "BrandName": "Minocin",
        "Class": "Tetracycline Antibiotic",
        "Use": "Bacterial infections, acne",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "100 mg BID",
        "SideEffects": "Dizziness, photosensitivity",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 114,
        "GenericName": "Montelukast",
        "BrandName": "Singulair",
        "Class": "Leukotriene Inhibitor",
        "Use": "Asthma, allergic rhinitis",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10 mg daily (asthma)",
        "SideEffects": "Headache, dizziness",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 115,
        "GenericName": "Mupirocin",
        "BrandName": "Bactroban",
        "Class": "Topical Antibiotic",
        "Use": "Skin infections (impetigo)",
        "DeliveryMechanism": "Topical",
        "Schedule": "Rx",
        "Dosage": "Apply 2-3x daily",
        "SideEffects": "Burning, stinging",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 116,
        "GenericName": "Mupirocin",
        "BrandName": "Bactroban",
        "Class": "Topical Antibiotic",
        "Use": "Skin infections (impetigo)",
        "DeliveryMechanism": "Topical",
        "Schedule": "Rx",
        "Dosage": "Apply 2-3x daily",
        "SideEffects": "Burning, stinging",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 117,
        "GenericName": "Mirtazapine",
        "BrandName": "Remeron",
        "Class": "Antidepressant",
        "Use": "Depression",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "15-45 mg daily",
        "SideEffects": "Weight gain, drowsiness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 118,
        "GenericName": "Nabumetone",
        "BrandName": "Relafen",
        "Class": "NSAID",
        "Use": "Pain, inflammation",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "500-1000 mg daily",
        "SideEffects": "GI upset, dizziness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 119,
        "GenericName": "Naproxen",
        "BrandName": "Naprosyn, Aleve",
        "Class": "NSAID",
        "Use": "Pain, inflammation",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC/Rx",
        "Dosage": "250-500 mg every 12 hours",
        "SideEffects": "GI upset, heartburn",
        "PregnancyCategory": "C",
        "Label": "otc/rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 120,
        "GenericName": "Nifedipine",
        "BrandName": "Procardia, Adalat",
        "Class": "Calcium Channel Blocker",
        "Use": "Hypertension, angina",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "30-90 mg daily",
        "SideEffects": "Dizziness, flushing",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 121,
        "GenericName": "Nitroglycerin",
        "BrandName": "Nitrostat, Nitrobid",
        "Class": "Nitrate",
        "Use": "Angina",
        "DeliveryMechanism": "Sublingual, Oral, Topical, IV",
        "Schedule": "Rx",
        "Dosage": "0.3-0.6 mg SL every 5 min PRN",
        "SideEffects": "Headache, hypotension",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 122,
        "GenericName": "Nortriptyline",
        "BrandName": "Pamelor",
        "Class": "Tricyclic Antidepressant",
        "Use": "Depression, neuropathic pain",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "25-75 mg daily",
        "SideEffects": "Dry mouth, drowsiness",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 123,
        "GenericName": "Olanzapine",
        "BrandName": "Zyprexa",
        "Class": "Atypical Antipsychotic",
        "Use": "Schizophrenia, bipolar disorder",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-20 mg daily",
        "SideEffects": "Weight gain, drowsiness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 124,
        "GenericName": "Omeprazole",
        "BrandName": "Prilosec",
        "Class": "Proton Pump Inhibitor",
        "Use": "GERD, acid reflux",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC/Rx",
        "Dosage": "20-40 mg daily",
        "SideEffects": "Headache, abdominal pain",
        "PregnancyCategory": "C",
        "Label": "otc/rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 125,
        "GenericName": "Ondansetron",
        "BrandName": "Zofran",
        "Class": "5-HT3 Antagonist",
        "Use": "Nausea, vomiting (especially chemotherapy-induced)",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "4-8 mg every 8 hours",
        "SideEffects": "Headache, constipation",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 126,
        "GenericName": "Oseltamivir",
        "BrandName": "Tamiflu",
        "Class": "Antiviral",
        "Use": "Influenza",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "75 mg BID for 5 days",
        "SideEffects": "Nausea, vomiting",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 127,
        "GenericName": "Oxybutynin",
        "BrandName": "Ditropan",
        "Class": "Anticholinergic",
        "Use": "Overactive bladder",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-10 mg BID",
        "SideEffects": "Dry mouth, constipation",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 128,
        "GenericName": "Oxycodone",
        "BrandName": "OxyContin, Roxicodone",
        "Class": "Opioid Analgesic",
        "Use": "Moderate to severe pain",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule II",
        "Dosage": "5-30 mg every 4-6 hours",
        "SideEffects": "Constipation, drowsiness",
        "PregnancyCategory": "C",
        "Label": "schedule-ii",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 129,
        "GenericName": "Pantoprazole",
        "BrandName": "Protonix",
        "Class": "Proton Pump Inhibitor",
        "Use": "GERD, acid reflux",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "20-40 mg daily",
        "SideEffects": "Headache, abdominal pain",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 130,
        "GenericName": "Paroxetine",
        "BrandName": "Paxil",
        "Class": "SSRI",
        "Use": "Depression, anxiety, OCD",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "20-60 mg daily",
        "SideEffects": "Nausea, sexual dysfunction",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 131,
        "GenericName": "Phenobarbital",
        "BrandName": NaN,
        "Class": "Barbiturate",
        "Use": "Seizures, anxiety",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Schedule IV",
        "Dosage": "30-120 mg daily",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "D",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 132,
        "GenericName": "Phenytoin",
        "BrandName": "Dilantin",
        "Class": "Anticonvulsant",
        "Use": "Seizures",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "100 mg TID",
        "SideEffects": "Dizziness, gum overgrowth",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 133,
        "GenericName": "Pioglitazone",
        "BrandName": "Actos",
        "Class": "Thiazolidinedione",
        "Use": "Type 2 Diabetes",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "15-45 mg daily",
        "SideEffects": "Weight gain, edema",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 134,
        "GenericName": "Polyethylene Glycol",
        "BrandName": "Miralax",
        "Class": "Osmotic Laxative",
        "Use": "Constipation",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC",
        "Dosage": "17 g daily",
        "SideEffects": "Bloating, diarrhea",
        "PregnancyCategory": "C",
        "Label": "otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 135,
        "GenericName": "Potassium Chloride",
        "BrandName": "Klor-Con, K-Dur",
        "Class": "Electrolyte",
        "Use": "Hypokalemia (low potassium)",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "20-100 mEq daily",
        "SideEffects": "GI discomfort, hyperkalemia",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 136,
        "GenericName": "Pravastatin",
        "BrandName": "Pravachol",
        "Class": "Statin",
        "Use": "High cholesterol",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-40 mg daily",
        "SideEffects": "Muscle pain, liver enzyme elevation",
        "PregnancyCategory": "X",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 137,
        "GenericName": "Prednisone",
        "BrandName": "Deltasone",
        "Class": "Corticosteroid",
        "Use": "Inflammation, autoimmune disorders",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-60 mg daily",
        "SideEffects": "Weight gain, mood changes",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 138,
        "GenericName": "Pregabalin",
        "BrandName": "Lyrica",
        "Class": "Anticonvulsant, Nerve Pain Agent",
        "Use": "Nerve pain, seizures, fibromyalgia",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule V",
        "Dosage": "75-300 mg BID",
        "SideEffects": "Dizziness, drowsiness",
        "PregnancyCategory": "C",
        "Label": "schedule-v",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 139,
        "GenericName": "Prochlorperazine",
        "BrandName": "Compazine",
        "Class": "Antipsychotic, Antiemetic",
        "Use": "Nausea, vomiting, schizophrenia",
        "DeliveryMechanism": "Oral, IV, Rectal",
        "Schedule": "Rx",
        "Dosage": "5-10 mg TID",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 140,
        "GenericName": "Propranolol",
        "BrandName": "Inderal",
        "Class": "Beta-blocker",
        "Use": "Hypertension, migraines, anxiety",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "40-160 mg BID",
        "SideEffects": "Dizziness, fatigue, bradycardia",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 141,
        "GenericName": "Quetiapine",
        "BrandName": "Seroquel",
        "Class": "Atypical Antipsychotic",
        "Use": "Schizophrenia, bipolar disorder",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "150-800 mg daily",
        "SideEffects": "Drowsiness, weight gain",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 142,
        "GenericName": "Quinapril",
        "BrandName": "Accupril",
        "Class": "ACE Inhibitor",
        "Use": "Hypertension, heart failure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-40 mg daily",
        "SideEffects": "Cough, dizziness",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 143,
        "GenericName": "Rabeprazole",
        "BrandName": "Aciphex",
        "Class": "Proton Pump Inhibitor",
        "Use": "GERD, acid reflux",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "20 mg daily",
        "SideEffects": "Headache, abdominal pain",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 144,
        "GenericName": "Ramipril",
        "BrandName": "Altace",
        "Class": "ACE Inhibitor",
        "Use": "Hypertension, heart failure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "2.5-20 mg daily",
        "SideEffects": "Cough, dizziness",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 145,
        "GenericName": "Ranolazine",
        "BrandName": "Ranexa",
        "Class": "Antianginal Agent",
        "Use": "Chronic angina",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "500-1000 mg BID",
        "SideEffects": "Dizziness, nausea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 146,
        "GenericName": "Ranitidine",
        "BrandName": "Zantac (recalled)",
        "Class": "H2 Receptor Antagonist",
        "Use": "GERD, acid reflux (currently recalled)",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC/Rx",
        "Dosage": "150 mg BID",
        "SideEffects": "Headache, constipation",
        "PregnancyCategory": "B",
        "Label": "otc/rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 147,
        "GenericName": "Rifaximin",
        "BrandName": "Xifaxan",
        "Class": "Antibiotic",
        "Use": "Traveler\u2019s diarrhea, IBS",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "200-550 mg TID",
        "SideEffects": "Bloating, nausea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 148,
        "GenericName": "Risperidone",
        "BrandName": "Risperdal",
        "Class": "Atypical Antipsychotic",
        "Use": "Schizophrenia, bipolar disorder",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "1-6 mg daily",
        "SideEffects": "Drowsiness, weight gain",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 149,
        "GenericName": "Rivaroxaban",
        "BrandName": "Xarelto",
        "Class": "Anticoagulant",
        "Use": "Stroke prevention, blood clots",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-20 mg daily",
        "SideEffects": "Bleeding, nausea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 150,
        "GenericName": "Rosuvastatin",
        "BrandName": "Crestor",
        "Class": "Statin",
        "Use": "High cholesterol",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-40 mg daily",
        "SideEffects": "Muscle pain, liver enzyme elevation",
        "PregnancyCategory": "X",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 151,
        "GenericName": "Salmeterol",
        "BrandName": "Serevent",
        "Class": "Beta-2 Agonist",
        "Use": "Asthma, COPD",
        "DeliveryMechanism": "Inhaler",
        "Schedule": "Rx",
        "Dosage": "50 mcg BID",
        "SideEffects": "Tremor, headache",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 152,
        "GenericName": "Sertraline",
        "BrandName": "Zoloft",
        "Class": "SSRI",
        "Use": "Depression, anxiety, OCD",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "50-200 mg daily",
        "SideEffects": "Nausea, insomnia, sexual dysfunction",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 153,
        "GenericName": "Sildenafil",
        "BrandName": "Viagra",
        "Class": "PDE5 Inhibitor",
        "Use": "Erectile dysfunction, pulmonary hypertension",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "25-100 mg PRN",
        "SideEffects": "Headache, flushing",
        "PregnancyCategory": "B (pulmonary), C (ED)",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 154,
        "GenericName": "Simvastatin",
        "BrandName": "Zocor",
        "Class": "Statin",
        "Use": "High cholesterol",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-40 mg daily",
        "SideEffects": "Muscle pain, liver enzyme elevation",
        "PregnancyCategory": "X",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 155,
        "GenericName": "Sitagliptin",
        "BrandName": "Januvia",
        "Class": "DPP-4 Inhibitor",
        "Use": "Type 2 Diabetes",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "100 mg daily",
        "SideEffects": "Nasopharyngitis, headache",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 156,
        "GenericName": "Spironolactone",
        "BrandName": "Aldactone",
        "Class": "Potassium-sparing Diuretic",
        "Use": "Hypertension, heart failure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "25-100 mg daily",
        "SideEffects": "Hyperkalemia, gynecomastia",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 157,
        "GenericName": "Sulfamethoxazole/Trimethoprim (Bactrim)",
        "BrandName": "Bactrim, Septra",
        "Class": "Antibiotic (Sulfonamide)",
        "Use": "Bacterial infections",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "800/160 mg BID",
        "SideEffects": "Rash, nausea",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 158,
        "GenericName": "Sumatriptan",
        "BrandName": "Imitrex",
        "Class": "Triptan",
        "Use": "Migraine",
        "DeliveryMechanism": "Oral, Injection, Nasal",
        "Schedule": "Rx",
        "Dosage": "50-100 mg at onset, may repeat",
        "SideEffects": "Dizziness, tingling sensation",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 159,
        "GenericName": "Tadalafil",
        "BrandName": "Cialis",
        "Class": "PDE5 Inhibitor",
        "Use": "Erectile dysfunction, pulmonary hypertension",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-20 mg PRN",
        "SideEffects": "Headache, flushing",
        "PregnancyCategory": "B (pulmonary), C (ED)",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 160,
        "GenericName": "Tamoxifen",
        "BrandName": "Nolvadex",
        "Class": "Selective Estrogen Receptor Modulator (SERM)",
        "Use": "Breast cancer prevention/treatment",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "20 mg daily",
        "SideEffects": "Hot flashes, nausea",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 161,
        "GenericName": "Telmisartan",
        "BrandName": "Micardis",
        "Class": "Angiotensin II Receptor Blocker (ARB)",
        "Use": "Hypertension",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "40-80 mg daily",
        "SideEffects": "Dizziness, hyperkalemia",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 162,
        "GenericName": "Terbinafine",
        "BrandName": "Lamisil",
        "Class": "Antifungal",
        "Use": "Fungal infections (e.g., athlete's foot)",
        "DeliveryMechanism": "Oral, Topical",
        "Schedule": "Rx",
        "Dosage": "250 mg daily (oral), Topical as directed",
        "SideEffects": "Headache, liver enzyme elevation",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 163,
        "GenericName": "Testosterone",
        "BrandName": "AndroGel, Testim",
        "Class": "Androgen",
        "Use": "Low testosterone (hypogonadism)",
        "DeliveryMechanism": "Topical, Injection",
        "Schedule": "Schedule III",
        "Dosage": "50-100 mg/day (Topical), 50-200 mg IM every 2-4 weeks",
        "SideEffects": "Acne, increased PSA",
        "PregnancyCategory": "X",
        "Label": "schedule-iii",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 164,
        "GenericName": "Tiotropium",
        "BrandName": "Spiriva",
        "Class": "Anticholinergic",
        "Use": "COPD, asthma",
        "DeliveryMechanism": "Inhaler",
        "Schedule": "Rx",
        "Dosage": "2 puffs (18 mcg) once daily",
        "SideEffects": "Dry mouth, throat irritation",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 165,
        "GenericName": "Tizanidine",
        "BrandName": "Zanaflex",
        "Class": "Muscle Relaxant",
        "Use": "Muscle spasms",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "2-4 mg TID",
        "SideEffects": "Drowsiness, dry mouth",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 166,
        "GenericName": "Topiramate",
        "BrandName": "Topamax",
        "Class": "Anticonvulsant",
        "Use": "Seizures, migraine prevention",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "25-200 mg BID",
        "SideEffects": "Drowsiness, weight loss",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 167,
        "GenericName": "Tramadol",
        "BrandName": "Ultram",
        "Class": "Opioid Analgesic",
        "Use": "Moderate to severe pain",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule IV",
        "Dosage": "50-100 mg every 4-6 hours",
        "SideEffects": "Drowsiness, constipation",
        "PregnancyCategory": "C",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 168,
        "GenericName": "Trazodone",
        "BrandName": "Desyrel",
        "Class": "Antidepressant",
        "Use": "Depression, insomnia",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "150-400 mg daily",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 169,
        "GenericName": "Triamcinolone",
        "BrandName": "Kenalog, Nasacort",
        "Class": "Corticosteroid",
        "Use": "Inflammation, allergic rhinitis",
        "DeliveryMechanism": "Oral, Topical, Nasal, Injection",
        "Schedule": "Rx",
        "Dosage": "Varies by formulation",
        "SideEffects": "Weight gain, mood changes",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 170,
        "GenericName": "Triamterene/Hydrochlorothiazide",
        "BrandName": "Dyazide, Maxzide",
        "Class": "Diuretic Combination",
        "Use": "Hypertension, edema",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "37.5/25 mg daily",
        "SideEffects": "Dizziness, dehydration",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 171,
        "GenericName": "Umeclidinium/Vilanterol",
        "BrandName": "Anoro Ellipta",
        "Class": "Anticholinergic/Beta-2 Agonist",
        "Use": "COPD",
        "DeliveryMechanism": "Inhaler",
        "Schedule": "Rx",
        "Dosage": "1 inhalation daily",
        "SideEffects": "Throat irritation, cough",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 172,
        "GenericName": "Ursodiol",
        "BrandName": "Actigall, Urso",
        "Class": "Bile Acid",
        "Use": "Gallstones, primary biliary cirrhosis",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "300 mg BID",
        "SideEffects": "Diarrhea, nausea",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 173,
        "GenericName": "Valacyclovir",
        "BrandName": "Valtrex",
        "Class": "Antiviral",
        "Use": "Herpes infections (cold sores, genital herpes)",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "500 mg-1 g BID",
        "SideEffects": "Nausea, headache",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 174,
        "GenericName": "Valproic Acid",
        "BrandName": "Depakene, Depakote",
        "Class": "Anticonvulsant, Mood Stabilizer",
        "Use": "Seizures, bipolar disorder",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "250-500 mg BID",
        "SideEffects": "Nausea, weight gain, hair loss",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 175,
        "GenericName": "Valsartan",
        "BrandName": "Diovan",
        "Class": "Angiotensin II Receptor Blocker (ARB)",
        "Use": "Hypertension, heart failure",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "80-320 mg daily",
        "SideEffects": "Dizziness, hyperkalemia",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 176,
        "GenericName": "Venlafaxine",
        "BrandName": "Effexor",
        "Class": "SNRI",
        "Use": "Depression, anxiety, panic disorders",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "75-225 mg daily",
        "SideEffects": "Nausea, insomnia, sexual dysfunction",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 177,
        "GenericName": "Verapamil",
        "BrandName": "Calan, Verelan",
        "Class": "Calcium Channel Blocker",
        "Use": "Hypertension, angina",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "120-480 mg daily",
        "SideEffects": "Dizziness, constipation",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 178,
        "GenericName": "Vitamin D3",
        "BrandName": "Cholecalciferol",
        "Class": "Supplement",
        "Use": "Vitamin D deficiency, bone health",
        "DeliveryMechanism": "Oral",
        "Schedule": "OTC",
        "Dosage": "1000-4000 IU daily",
        "SideEffects": "Nausea, hypercalcemia",
        "PregnancyCategory": "C",
        "Label": "otc",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 179,
        "GenericName": "Voriconazole",
        "BrandName": "Vfend",
        "Class": "Antifungal",
        "Use": "Fungal infections",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "200 mg BID",
        "SideEffects": "Vision changes, liver toxicity",
        "PregnancyCategory": "D",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 180,
        "GenericName": "Warfarin",
        "BrandName": "Coumadin",
        "Class": "Anticoagulant",
        "Use": "Stroke prevention, blood clots",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "Individualized (based on INR)",
        "SideEffects": "Bleeding, bruising",
        "PregnancyCategory": "X",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 181,
        "GenericName": "Xarelto",
        "BrandName": "Rivaroxaban",
        "Class": "Anticoagulant",
        "Use": "Stroke prevention, blood clots",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "10-20 mg daily",
        "SideEffects": "Bleeding, nausea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 182,
        "GenericName": "Xanax",
        "BrandName": "Alprazolam",
        "Class": "Benzodiazepine",
        "Use": "Anxiety, panic disorders",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule IV",
        "Dosage": "0.25-2 mg TID",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "D",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 183,
        "GenericName": "Xylocaine",
        "BrandName": "Lidocaine",
        "Class": "Local Anesthetic",
        "Use": "Local anesthesia, pain relief",
        "DeliveryMechanism": "Topical, Injection",
        "Schedule": "Rx",
        "Dosage": "5% patch, as directed (topical)",
        "SideEffects": "Numbness, redness",
        "PregnancyCategory": "B (topical), C (injection)",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 184,
        "GenericName": "Yohimbine",
        "BrandName": "Aphrodyne, Yocon",
        "Class": "Alpha-2 Antagonist",
        "Use": "Erectile dysfunction, weight loss",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "5-10 mg TID",
        "SideEffects": "Anxiety, increased heart rate",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 185,
        "GenericName": "Zolpidem",
        "BrandName": "Ambien",
        "Class": "Hypnotic",
        "Use": "Insomnia",
        "DeliveryMechanism": "Oral",
        "Schedule": "Schedule IV",
        "Dosage": "5-10 mg before bedtime",
        "SideEffects": "Drowsiness, dizziness",
        "PregnancyCategory": "C",
        "Label": "schedule-iv",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 186,
        "GenericName": "Zonisamide",
        "BrandName": "Zonegran",
        "Class": "Anticonvulsant",
        "Use": "Seizures",
        "DeliveryMechanism": "Oral",
        "Schedule": "Rx",
        "Dosage": "100-400 mg daily",
        "SideEffects": "Dizziness, drowsiness, weight loss",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 187,
        "GenericName": "Zoster Vaccine",
        "BrandName": "Zostavax",
        "Class": "Vaccine",
        "Use": "Shingles prevention",
        "DeliveryMechanism": "Injection",
        "Schedule": "Rx",
        "Dosage": "0.65 mL (single dose)",
        "SideEffects": "Injection site pain, headache",
        "PregnancyCategory": "B",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 188,
        "GenericName": "Zidovudine",
        "BrandName": "Retrovir",
        "Class": "Antiretroviral",
        "Use": "HIV infection",
        "DeliveryMechanism": "Oral, IV",
        "Schedule": "Rx",
        "Dosage": "300 mg BID",
        "SideEffects": "Headache, nausea",
        "PregnancyCategory": "C",
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 189,
        "GenericName": "Dexcom G6",
        "BrandName": "Dexcom",
        "Class": "Continuous Glucose Monitor (CGM)",
        "Use": "Continuous blood glucose monitoring for diabetes management",
        "DeliveryMechanism": "Subcutaneous Sensor",
        "Schedule": "OTC/Rx",
        "Dosage": "Replace sensor every 10 days",
        "SideEffects": "Skin irritation, infection at insertion site",
        "PregnancyCategory": NaN,
        "Label": "otc/rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 190,
        "GenericName": "Freestyle Libre 2",
        "BrandName": "Freestyle Libre",
        "Class": "Continuous Glucose Monitor (CGM)",
        "Use": "Continuous blood glucose monitoring for diabetes management",
        "DeliveryMechanism": "Subcutaneous Sensor",
        "Schedule": "OTC/Rx",
        "Dosage": "Replace sensor every 14 days",
        "SideEffects": "Skin irritation, discomfort",
        "PregnancyCategory": NaN,
        "Label": "otc/rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 191,
        "GenericName": "Eversense CGM System",
        "BrandName": "Eversense",
        "Class": "Continuous Glucose Monitor (CGM)",
        "Use": "Continuous blood glucose monitoring for diabetes management",
        "DeliveryMechanism": "Implantable Sensor",
        "Schedule": "Rx",
        "Dosage": "Sensor lasts up to 90 days",
        "SideEffects": "Skin irritation, mild pain at insertion site",
        "PregnancyCategory": NaN,
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    },
    {
        "Id": 192,
        "GenericName": "Medtronic Guardian Connect",
        "BrandName": "Medtronic",
        "Class": "Continuous Glucose Monitor (CGM)",
        "Use": "Continuous blood glucose monitoring for diabetes management",
        "DeliveryMechanism": "Subcutaneous Sensor",
        "Schedule": "Rx",
        "Dosage": "Replace sensor every 7 days",
        "SideEffects": "Skin irritation, sensor adhesion issues",
        "PregnancyCategory": NaN,
        "Label": "rx",
        "Date": "10-18-2024",
        "deleted": false
    }
];

mock.onGet('/api/data/item/ItemData').reply(() => {
  return [200, ItemData];
});
export default ItemData;
