-- Pharmacists Data Migration
-- Generated on 2025-06-24T04:42:13.126Z
-- Total records: 15

BEGIN;

-- Clear existing data (optional - uncomment if needed)
-- DELETE FROM pharmacists;

-- Pharmacist 1: John Doe
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-1-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'John',
    null,
    'Doe',
    '456-485-5623',
    'johndoe@pharmacy.com',
    'Specializes in oncology medication management',
    'clinical',
    'AB1234567',
    '1234567890',
    'PH12345',
    '2025-06-30',
    15,
    'English, Spanish'
);

-- Pharmacist 2: Jane Smith
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-2-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Jane',
    null,
    'Smith',
    '999-895-9652',
    'janesmith@cvs.com',
    'Focus on chronic disease management',
    'staff',
    'AC9876543',
    '9876543210',
    'PH67890',
    '2026-03-15',
    10,
    'English'
);

-- Pharmacist 3: Albert Johnson
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-3-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Albert',
    null,
    'Johnson',
    '789-854-8950',
    'ajohnson@customrx.com',
    'Expert in sterile compounding',
    'compounding',
    'BC7654321',
    '3456789012',
    'PH09876',
    '2024-11-22',
    8,
    'English, French'
);

-- Pharmacist 4: Emily Clark
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-4-1750740133134',
    now(),
    1,
    now(),
    1,
    true,
    now(),
    1,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Emily',
    null,
    'Clark',
    '452-652-5230',
    'eclark@kp.org',
    'Specializes in pediatrics',
    'clinical',
    'CD6543210',
    '5678901234',
    'PH54321',
    '2023-09-01',
    12,
    'English'
);

-- Pharmacist 5: David Brown
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-5-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'David',
    null,
    'Brown',
    '985-985-7850',
    'dbrown@mountsinai.com',
    'Focus on emergency medicine',
    'hospital',
    'EF6543219',
    '6543210987',
    'PH23456',
    '2027-01-12',
    18,
    'English, German'
);

-- Pharmacist 6: Sophia Davis
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-6-1750740133134',
    now(),
    1,
    now(),
    1,
    true,
    now(),
    1,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Sophia',
    null,
    'Davis',
    '230-541-5231',
    'sdavis@riteaid.com',
    'Chronic care management specialist',
    'staff',
    'FG8765432',
    '1230987654',
    'PH76543',
    '2025-07-25',
    14,
    'English'
);

-- Pharmacist 7: Olivia Miller
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-7-1750740133134',
    now(),
    1,
    now(),
    1,
    true,
    now(),
    1,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Olivia',
    null,
    'Miller',
    '478-582-6520',
    'omiller@cvs.com',
    'Specializes in patient education',
    'staff',
    'GH9876543',
    '1239876543',
    'PH76544',
    '2026-08-18',
    7,
    'English, Spanish'
);

-- Pharmacist 8: Noah Williams
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-8-1750740133134',
    now(),
    1,
    now(),
    1,
    true,
    now(),
    1,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Noah',
    null,
    'Williams',
    '123-652-2301',
    'nwilliams@cedars-sinai.com',
    'Focus on critical care pharmacy',
    'hospital',
    'HI8765432',
    '6540987654',
    'PH65432',
    '2025-12-10',
    11,
    'English'
);

-- Pharmacist 9: Liam Jones
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-9-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Liam',
    null,
    'Jones',
    '652-452-6521',
    'ljones@mayoclinic.org',
    'Expert in cardiology medication',
    'clinical',
    'IJ7654321',
    '0987654321',
    'PH54322',
    '2024-04-28',
    13,
    'English'
);

-- Pharmacist 10: Emma Taylor
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-10-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Emma',
    null,
    'Taylor',
    '789-123-4567',
    'etaylor@walgreens.com',
    'Specializes in diabetes management',
    'staff',
    'JK1234567',
    '1122334455',
    'PH87654',
    '2026-09-15',
    9,
    'English, Spanish'
);

-- Pharmacist 11: Ava Anderson
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-11-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Ava',
    null,
    'Anderson',
    '555-123-4567',
    'aanderson@customrx.com',
    'Expert in hormone replacement therapy',
    'compounding',
    'LM9876543',
    '2233445566',
    'PH23457',
    '2025-11-30',
    16,
    'English'
);

-- Pharmacist 12: Mason Wilson
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-12-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Mason',
    null,
    'Wilson',
    '410-555-1234',
    'mwilson@jhmi.edu',
    'Focus on transplant medications',
    'hospital',
    'NO4567890',
    '3344556677',
    'PH34567',
    '2027-03-20',
    20,
    'English, French'
);

-- Pharmacist 13: Isabella Thomas
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-13-1750740133134',
    now(),
    1,
    now(),
    1,
    true,
    now(),
    1,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Isabella',
    null,
    'Thomas',
    '617-555-9876',
    'ithomas@cvs.com',
    'Specializes in geriatric care',
    'staff',
    'PQ7890123',
    '4455667788',
    'PH45678',
    '2024-12-31',
    11,
    'English, Italian'
);

-- Pharmacist 14: Ethan Jackson
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-14-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Ethan',
    null,
    'Jackson',
    '216-555-4321',
    'ejackson@ccf.org',
    'Expert in infectious diseases',
    'clinical',
    'RS0123456',
    '5566778899',
    'PH56789',
    '2026-06-15',
    14,
    'English'
);

-- Pharmacist 15: Mia White
INSERT INTO pharmacists (
    uuid,
    slug,
    created_on,
    created_by,
    updated_on,
    updated_by,
    deleted,
    deleted_on,
    deleted_by,
    visibility,
    version,
    previous_id,
    change_log,
    status,
    first_name,
    middle_initial,
    last_name,
    phone,
    email,
    notes,
    type,
    dea_number,
    npi_number,
    license_number,
    license_expiration,
    years_experience,
    languages_spoken
) VALUES (
    gen_random_uuid(),
    'pharmacist-15-1750740133134',
    now(),
    1,
    now(),
    1,
    false,
    null,
    null,
    'public',
    1,
    null,
    'Initial migration from mock data',
    'active',
    'Mia',
    null,
    'White',
    '305-555-6789',
    'mwhite@riteaid.com',
    'Specializes in pain management',
    'staff',
    'TU3456789',
    '6677889900',
    'PH67891',
    '2025-08-22',
    8,
    'English, Spanish'
);

COMMIT;

-- Verify the migration
SELECT COUNT(*) as total_pharmacists FROM pharmacists;
SELECT COUNT(*) as active_pharmacists FROM pharmacists WHERE deleted = false;
SELECT COUNT(*) as archived_pharmacists FROM pharmacists WHERE deleted = true;

-- Show sample of administrative data
SELECT 
    id,
    first_name,
    last_name,
    created_by,
    created_on,
    updated_by,
    updated_on,
    status,
    version
FROM pharmacists 
LIMIT 5;
