import mock from '../mock';

export const requestLists = [
  {
    id: 101,
    patientfirstname: 'Georgeanna',
    patientmiddleInitial: 'A',
    patientlastname: 'Ramero',
    patientdob: '08/23/1986',
    patientemail: 'first@xabz.com',
    patientphone: '979-796-7865',
    patientaddress: '19214 110th Rd',
    patientaddress2: '',
    patientcity: 'Saint Albans',
    patientstate: 'NY',
    patientzipcode: '11412',
    patientinsurance1: 'Aetna',
    patientinsurance1ID: '568585',
    patientinsurance2: 'Humana',
    patientinsurance2ID: '935935995',
    patientnotes: 'Devolved Tangible Projection',
    pharmacyname: 'CVS Hartford 46',
    pharmacyaddress: '19214 110th Rd, Saint Albans, NY, 11412',
    doctorname: 'Andrew Albright',
    doctorpractice: 'Smile Brightly MD',
    doctorfax: '979-796-7865',
    doctoraddress: 'Godrej garden city,Ahmedabad.',
    doctorphone: '979-796-7865',
    doctorNPI: '538957573',
    doctorDEA: '3563635',
    doctorofficecontact: '3563635',
    doctornotes: '3563635',
    orderitem: 'Dapagliflozin',
    orderdosage: '5mg',
    orderquantity: '30 (thirty)',
    orderusage: 'Take 2 tablets orally twice daily',
    orderDate: new Date(),
    status: 'Processing',
    completed: false,
    isSelected: false,
  },
  {
    id: 102,
    patientfirstname: 'Alexandra',
    patientmiddleInitial: 'B',
    patientlastname: 'Johnson',
    patientdob: '03/15/1992',
    patientemail: 'alex.johnson@email.com',
    patientphone: '818-555-2345',
    patientaddress: '123 Elm St',
    patientaddress2: 'Apt 4B',
    patientcity: 'Brooklyn',
    patientstate: 'NY',
    patientzipcode: '11201',
    patientinsurance1: 'Cigna',
    patientinsurance1ID: 'A123456',
    patientinsurance2: '',
    patientinsurance2ID: '',
    patientnotes: 'Needs follow-up for blood pressure check',
    pharmacyname: 'Walgreens Brooklyn Heights',
    pharmacyaddress: '123 Elm St, Brooklyn, NY, 11201',
    doctorname: 'David Patel',
    doctorpractice: 'Brooklyn Family Practice',
    doctorfax: '818-555-6789',
    doctoraddress: '456 Pine Ave, Brooklyn, NY, 11201',
    doctorphone: '818-555-6789',
    doctorNPI: '9988776655',
    doctorDEA: 'ABC1234567',
    doctorofficecontact: 'John Doe',
    doctornotes: 'Reviewed lab results, follow-up next week',
    orderitem: 'Lisinopril',
    orderdosage: '10mg',
    orderquantity: '90 (ninety)',
    orderusage: 'Take 1 tablet orally once daily',
    orderDate: new Date(),
    status: 'Complete',
    completed: true,
    isSelected: false
},
{
    id: 103,
    patientfirstname: 'Michael',
    patientmiddleInitial: 'C',
    patientlastname: 'Garcia',
    patientdob: '11/05/1980',
    patientemail: 'michael.garcia@email.com',
    patientphone: '305-555-5678',
    patientaddress: '789 Ocean Dr',
    patientaddress2: '',
    patientcity: 'Miami Beach',
    patientstate: 'FL',
    patientzipcode: '33139',
    patientinsurance1: 'United Healthcare',
    patientinsurance1ID: 'UHC987654',
    patientinsurance2: '',
    patientinsurance2ID: '',
    patientnotes: 'Allergic to penicillin',
    pharmacyname: 'Publix Pharmacy',
    pharmacyaddress: '789 Ocean Dr, Miami Beach, FL, 33139',
    doctorname: 'Sarah Wong',
    doctorpractice: 'Oceanfront Medical Group',
    doctorfax: '305-555-8765',
    doctoraddress: '101 Bayview Ave, Miami Beach, FL, 33139',
    doctorphone: '305-555-8765',
    doctorNPI: '1122334455',
    doctorDEA: 'XYZ8765432',
    doctorofficecontact: 'Jane Smith',
    doctornotes: 'Patient to return in 3 months for cholesterol check',
    orderitem: 'Atorvastatin',
    orderdosage: '20mg',
    orderquantity: '30 (thirty)',
    orderusage: 'Take 1 tablet orally once daily',
    orderDate: new Date(),
    status: 'Created',
    completed: false,
    isSelected: false
},
{
    id: 104,
    patientfirstname: 'Jessica',
    patientmiddleInitial: 'D',
    patientlastname: 'Martinez',
    patientdob: '07/12/1978',
    patientemail: 'jessica.martinez@email.com',
    patientphone: '602-555-4321',
    patientaddress: '456 Sunset Blvd',
    patientaddress2: 'Unit 2A',
    patientcity: 'Phoenix',
    patientstate: 'AZ',
    patientzipcode: '85004',
    patientinsurance1: 'Blue Cross',
    patientinsurance1ID: 'BC567890',
    patientinsurance2: 'Aetna',
    patientinsurance2ID: 'AET1234567',
    patientnotes: 'Recent surgery, requires pain management',
    pharmacyname: 'CVS Pharmacy Downtown',
    pharmacyaddress: '456 Sunset Blvd, Phoenix, AZ, 85004',
    doctorname: 'Emily Rodriguez',
    doctorpractice: 'Sunset Medical Group',
    doctorfax: '602-555-6789',
    doctoraddress: '321 Maple Ave, Phoenix, AZ, 85004',
    doctorphone: '602-555-6789',
    doctorNPI: '3344556677',
    doctorDEA: 'DEA8765432',
    doctorofficecontact: 'Tom Rogers',
    doctornotes: 'Patient recovering well, continue current meds',
    orderitem: 'Oxycodone',
    orderdosage: '5mg',
    orderquantity: '60 (sixty)',
    orderusage: 'Take 1 tablet orally every 6 hours as needed',
    orderDate: new Date(),
    status: 'Processing',
    completed: false,
    isSelected: false
},
{
    id: 105,
    patientfirstname: 'Daniel',
    patientmiddleInitial: 'E',
    patientlastname: 'Lee',
    patientdob: '04/25/1965',
    patientemail: 'daniel.lee@email.com',
    patientphone: '415-555-1234',
    patientaddress: '789 Market St',
    patientaddress2: '',
    patientcity: 'San Francisco',
    patientstate: 'CA',
    patientzipcode: '94103',
    patientinsurance1: 'Medicare',
    patientinsurance1ID: 'MC123456789',
    patientinsurance2: '',
    patientinsurance2ID: '',
    patientnotes: 'Requires diabetic supplies',
    pharmacyname: 'Rite Aid SF',
    pharmacyaddress: '789 Market St, San Francisco, CA, 94103',
    doctorname: 'Lisa Kim',
    doctorpractice: 'Bay Area Health Clinic',
    doctorfax: '415-555-6789',
    doctoraddress: '123 Castro St, San Francisco, CA, 94103',
    doctorphone: '415-555-6789',
    doctorNPI: '2233445566',
    doctorDEA: 'DEA1234567',
    doctorofficecontact: 'Nancy Drew',
    doctornotes: 'Update glucose monitor prescription',
    orderitem: 'Insulin Glargine',
    orderdosage: '100 units/mL',
    orderquantity: '3 vials',
    orderusage: 'Inject 10 units subcutaneously every evening',
    orderDate: new Date(),
    status: 'Created',
    completed: true,
    isSelected: false
},
  {
    id: 106,
    patientfirstname: 'Rebecca',
    patientmiddleInitial: 'F',
    patientlastname: 'Morris',
    patientdob: '02/19/1975',
    patientemail: 'rebecca.morris@email.com',
    patientphone: '212-555-9876',
    patientaddress: '234 Lexington Ave',
    patientaddress2: 'Apt 5C',
    patientcity: 'New York',
    patientstate: 'NY',
    patientzipcode: '10016',
    patientinsurance1: 'Empire BlueCross',
    patientinsurance1ID: 'EBX87654',
    patientinsurance2: '',
    patientinsurance2ID: '',
    patientnotes: 'Requires refill for chronic migraines',
    pharmacyname: 'Duane Reade Midtown',
    pharmacyaddress: '234 Lexington Ave, New York, NY, 10016',
    doctorname: 'Matthew Green',
    doctorpractice: 'Manhattan Neurology',
    doctorfax: '212-555-1234',
    doctoraddress: '567 Park Ave, New York, NY, 10022',
    doctorphone: '212-555-1234',
    doctorNPI: '7766554433',
    doctorDEA: 'DEA7654321',
    doctorofficecontact: 'Sarah Finch',
    doctornotes: 'Discussed alternative migraine treatments',
    orderitem: 'Sumatriptan',
    orderdosage: '100mg',
    orderquantity: '9 (nine)',
    orderusage: 'Take 1 tablet orally at onset of migraine',
    orderDate: new Date(),
    status: 'Complete',
    completed: false,
    isSelected: false
},
{
    id: 107,
    patientfirstname: 'Charles',
    patientmiddleInitial: 'G',
    patientlastname: 'Harrison',
    patientdob: '10/03/1952',
    patientemail: 'charles.harrison@email.com',
    patientphone: '502-555-3344',
    patientaddress: '678 Oakwood Dr',
    patientaddress2: '',
    patientcity: 'Louisville',
    patientstate: 'KY',
    patientzipcode: '40207',
    patientinsurance1: 'Humana',
    patientinsurance1ID: 'HUM123654',
    patientinsurance2: 'Medicare',
    patientinsurance2ID: 'MC654321',
    patientnotes: 'Requires heart medication renewal',
    pharmacyname: 'Kroger Pharmacy Louisville',
    pharmacyaddress: '678 Oakwood Dr, Louisville, KY, 40207',
    doctorname: 'Brian Smith',
    doctorpractice: 'Louisville Cardiology',
    doctorfax: '502-555-6789',
    doctoraddress: '123 Derby Ln, Louisville, KY, 40207',
    doctorphone: '502-555-6789',
    doctorNPI: '3344556677',
    doctorDEA: 'DEA4567890',
    doctorofficecontact: 'Melissa Hart',
    doctornotes: 'Patient stable, continue current meds',
    orderitem: 'Metoprolol',
    orderdosage: '50mg',
    orderquantity: '60 (sixty)',
    orderusage: 'Take 1 tablet orally twice daily',
    orderDate: new Date(),
    status: 'Processing',
    completed: false,
    isSelected: false
}
];

mock.onGet('/api/data/requestdata').reply(() => {
  return [200, requestLists];
});

mock.onDelete('/api/data/requestdata/deleterequest').reply((config) => {
  const { requestId } = JSON.parse(config.data);
  const requestIndex = requestLists.findIndex((request) => request.id === requestId);
  if (requestIndex !== -1) {
    requestLists.splice(requestIndex, 1);
    return [200, requestLists];
  } else {
    return [404, { message: 'Request not found' }];
  }
});
// Function to find the next available ID
const getNextId = () => {
  const maxId = Math.max(...requestLists.map((request) => request.id));
  return maxId + 1;
};
// New endpoint to add a request
mock.onPost('/api/data/requestdata/addrequest').reply((config) => {
  const newRequest = JSON.parse(config.data);
  newRequest.id = getNextId();
  requestLists.push(newRequest);
  return [201, newRequest];
});

// Mock API endpoint to update a request
mock.onPut('/api/data/requestdata/updaterequest').reply((config) => {
  const updatedRequest = JSON.parse(config.data);
  const requestIndex = requestLists.findIndex((request) => request.id === updatedRequest.id);

  if (requestIndex !== -1) {
    requestLists[requestIndex] = { ...updatedRequest };
    return [200, requestLists[requestIndex]];
  } else {
    return [404, { message: 'Request not found' }];
  }
});

