const APP_BASE_URL = process.env.APP_BASE_URL || 'http://localhost:5174';

export function buildRequestPayload(details) {
  const request = {
    id: details.id,
    uuid: details.uuid || null,
    status: details.status,
    notes: details.notes,
    requested_date: details.requested_date,
    completed_date: details.completed_date,
    pharmacy_id: details.pharmacy_id,
    patient_id: details.patient_id,
    physician_id: details.physician_id,
    item_id: details.item_id,
    created_on: details.created_on,
    updated_on: details.updated_on,
    visibility: details.visibility,
    version: details.version,
    change_log: details.change_log,
    llm_conversation: details.llm_conversation,
  };

  const item = details.item_id ? {
    id: details.item_id,
    uuid: details.item_uuid || null,
    brand_name: details.item_brand_name || details.item_brand || details.brand_name || null,
    generic_name: details.item_generic_name || details.generic_name || null,
    class: details.item_class || null,
    use_description: details.item_use_description || null,
    delivery_mechanism: details.item_delivery_mechanism || null,
    schedule: details.item_schedule || null,
    dosage: details.item_dosage || null,
    side_effects: details.item_side_effects || null,
    pregnancy_category: details.item_pregnancy_category || null,
    label: details.item_label || null,
    date_added: details.item_date_added || null,
    status: details.item_status || null,
  } : null;

  const pharmacy = details.pharmacy_id ? {
    id: details.pharmacy_id,
    uuid: details.pharmacy_uuid || null,
    name: details.pharmacy_name || null,
    pharmacy_type: details.pharmacy_type || null,
    phone: details.pharmacy_phone || null,
    fax: details.pharmacy_fax || null,
    email: details.pharmacy_email || null,
    website: details.pharmacy_website || null,
    address: details.pharmacy_address || null,
    business_hours: details.pharmacy_business_hours || null,
    license_number: details.pharmacy_license_number || null,
    license_expiration: details.pharmacy_license_expiration || null,
    npi_number: details.pharmacy_npi_number || null,
    insurance_accepted: details.pharmacy_insurance_accepted || null,
    services_offered: details.pharmacy_services_offered || null,
    pharmacy_chain: details.pharmacy_chain || null,
    manager_name: details.pharmacy_manager_name || null,
    status: details.pharmacy_status || null,
  } : null;

  const links = {
    request_admin_url: `${APP_BASE_URL}/admin/requests/${details.id}`,
    request_pharmacy_url: `${APP_BASE_URL}/requests/${details.id}`,
  };

  const patient = details.patient_id ? {
    id: details.patient_id,
    uuid: details.patient_uuid || null,
    first_name: details.patient_first_name || null,
    middle_initial: details.patient_middle_initial || null,
    last_name: details.patient_last_name || null,
    email: details.patient_email || null,
    phone: details.patient_phone || null,
    dob: details.patient_dob || null,
    gender: details.patient_gender || null,
    address: details.patient_address || null,
    address2: details.patient_address2 || null,
    city: details.patient_city || null,
    state: details.patient_state || null,
    zipcode: details.patient_zipcode || null,
    insurance1: details.patient_insurance1 || null,
    insurance1_id: details.patient_insurance1_id || null,
    insurance2: details.patient_insurance2 || null,
    insurance2_id: details.patient_insurance2_id || null,
    notes: details.patient_notes || null,
    status: details.patient_status || null,
  } : null;

  const physician = details.physician_id ? {
    id: details.physician_id,
    uuid: details.physician_uuid || null,
    first_name: details.physician_first_name || null,
    middle_initial: details.physician_middle_initial || null,
    last_name: details.physician_last_name || null,
    suffix: details.physician_suffix || null,
    title: details.physician_title || null,
    specialty: details.physician_specialty || null,
    sub_specialty: details.physician_sub_specialty || null,
    practice_type: details.physician_practice_type || null,
    phone: details.physician_phone || null,
    fax: details.physician_fax || null,
    email: details.physician_email || null,
    website: details.physician_website || null,
    address: details.physician_address || null,
    address2: details.physician_address2 || null,
    city: details.physician_city || null,
    state: details.physician_state || null,
    zipcode: details.physician_zipcode || null,
    country: details.physician_country || null,
    npi_number: details.physician_npi || null,
    dea_number: details.physician_dea_number || null,
    license_number: details.physician_license_number || null,
    license_expiration: details.physician_license_expiration || null,
    board_certifications: details.physician_board_certifications || null,
    languages_spoken: details.physician_languages_spoken || null,
    years_of_experience: details.physician_years_of_experience || null,
    practice_name: details.physician_practice_name || null,
    practice_address: details.physician_practice_address || null,
    practice_city: details.physician_practice_city || null,
    practice_state: details.physician_practice_state || null,
    practice_zipcode: details.physician_practice_zipcode || null,
    practice_phone: details.physician_practice_phone || null,
    practice_fax: details.physician_practice_fax || null,
    practice_website: details.physician_practice_website || null,
    insurance_accepted: details.physician_insurance_accepted || null,
    accepting_new_patients: details.physician_accepting_new_patients || null,
    appointment_required: details.physician_appointment_required || null,
    notes: details.physician_notes || null,
    frequently_contacted: details.physician_frequently_contacted || null,
    starred: details.physician_starred || null,
    affiliated_hospitals: details.physician_affiliated_hospitals || null,
    affiliated_pharmacies: details.physician_affiliated_pharmacies || null,
    status: details.physician_status || null,
  } : null;

  return { request, pharmacy, item, patient, physician, links, schema_version: 2 };
}

export function buildFaxPayload(fax) {
  return {
    fax: {
      id: fax.id,
      telnyx_fax_id: fax.telnyx_fax_id || null,
      request_id: fax.request_id || fax.requests || null,
      direction: fax.direction || fax.type || null,
      status: fax.status,
      sent_to: fax.sent_to || fax.fax_number || null,
      sent_by: fax.sent_by || null,
      doc_link: fax.doc_link || null,
      created_on: fax.created_on,
      updated_on: fax.updated_on,
    },
    schema_version: 1,
  };
}

export function buildPatientPayload(patient) {
  return {
    patient: {
      id: patient.id,
      uuid: patient.uuid || null,
      first_name: patient.first_name,
      middle_initial: patient.middle_initial || null,
      last_name: patient.last_name,
      email: patient.email,
      phone: patient.phone,
      dob: patient.dob,
      gender: patient.gender,
      address: patient.address,
      address2: patient.address2 || null,
      city: patient.city,
      state: patient.state,
      zipcode: patient.zipcode,
      insurance1: patient.insurance1,
      insurance1_id: patient.insurance1_id,
      insurance2: patient.insurance2 || null,
      insurance2_id: patient.insurance2_id || null,
      notes: patient.notes || null,
      status: patient.status,
      created_on: patient.created_on,
      updated_on: patient.updated_on,
    },
    schema_version: 1,
  };
}

export function buildPhysicianPayload(physician) {
  return {
    physician: {
      id: physician.id,
      uuid: physician.uuid || null,
      first_name: physician.first_name,
      middle_initial: physician.middle_initial || null,
      last_name: physician.last_name,
      suffix: physician.suffix || null,
      title: physician.title || null,
      specialty: physician.specialty || null,
      sub_specialty: physician.sub_specialty || null,
      practice_type: physician.practice_type || null,
      phone: physician.phone || null,
      fax: physician.fax || null,
      email: physician.email || null,
      website: physician.website || null,
      address: physician.address || null,
      address2: physician.address2 || null,
      city: physician.city || null,
      state: physician.state || null,
      zipcode: physician.zipcode || null,
      country: physician.country || null,
      npi_number: physician.npi_number || null,
      dea_number: physician.dea_number || null,
      license_number: physician.license_number || null,
      license_expiration: physician.license_expiration || null,
      board_certifications: physician.board_certifications || null,
      languages_spoken: physician.languages_spoken || null,
      years_of_experience: physician.years_of_experience || null,
      practice_name: physician.practice_name || null,
      practice_address: physician.practice_address || null,
      practice_city: physician.practice_city || null,
      practice_state: physician.practice_state || null,
      practice_zipcode: physician.practice_zipcode || null,
      practice_phone: physician.practice_phone || null,
      practice_fax: physician.practice_fax || null,
      practice_website: physician.practice_website || null,
      insurance_accepted: physician.insurance_accepted || null,
      accepting_new_patients: physician.accepting_new_patients || null,
      appointment_required: physician.appointment_required || null,
      notes: physician.notes || null,
      frequently_contacted: physician.frequently_contacted || null,
      starred: physician.starred || null,
      affiliated_hospitals: physician.affiliated_hospitals || null,
      affiliated_pharmacies: physician.affiliated_pharmacies || null,
      status: physician.status,
      created_on: physician.created_on,
      updated_on: physician.updated_on,
    },
    schema_version: 1,
  };
}

export function buildPharmacyPayload(pharmacy) {
  return {
    pharmacy: {
      id: pharmacy.id,
      uuid: pharmacy.uuid || null,
      pharmacy_name: pharmacy.pharmacy_name,
      pharmacy_type: pharmacy.pharmacy_type,
      phone: pharmacy.phone || null,
      fax: pharmacy.fax || null,
      email: pharmacy.email || null,
      website: pharmacy.website || null,
      address: pharmacy.address || null,
      business_hours: pharmacy.business_hours || null,
      license_number: pharmacy.license_number || null,
      license_expiration: pharmacy.license_expiration || null,
      npi_number: pharmacy.npi_number || null,
      insurance_accepted: pharmacy.insurance_accepted || null,
      services_offered: pharmacy.services_offered || null,
      pharmacy_chain: pharmacy.chain_name || null,
      manager_name: pharmacy.contact_person || null,
      notes: pharmacy.notes || null,
      status: pharmacy.status,
      created_on: pharmacy.created_on,
      updated_on: pharmacy.updated_on,
    },
    schema_version: 1,
  };
}

export function buildItemPayload(item) {
  return {
    item: {
      id: item.id,
      uuid: item.uuid || null,
      generic_name: item.generic_name,
      brand_name: item.brand_name || null,
      class: item.class || null,
      use_description: item.use_description || null,
      delivery_mechanism: item.delivery_mechanism || null,
      schedule: item.schedule || null,
      dosage: item.dosage || null,
      side_effects: item.side_effects || null,
      pregnancy_category: item.pregnancy_category || null,
      label: item.label || null,
      date_added: item.date_added || null,
      status: item.status,
      created_on: item.created_on,
      updated_on: item.updated_on,
    },
    schema_version: 1,
  };
}


