import mock from '../mock';
import user1 from 'src/assets/images/profile/user-1.jpg';
import user2 from 'src/assets/images/profile/user-2.jpg';
import user3 from 'src/assets/images/profile/user-3.jpg';
import user4 from 'src/assets/images/profile/user-4.jpg';
import user5 from 'src/assets/images/profile/user-5.jpg';

export const PhysicianList = [
  {
    id: 1,
    firstname: 'John',
    middle_initial: 'A',
    lastname: 'Doe',
    image: user2,
    type: 'Clinical Pharmacy',
    business_name: 'Walgreens',
    phone: '456-485-5623',
    email: 'johndoe@business_name.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Specializes in oncology medication management',
    fax: 'AB1234567',
    licenseNumber: 'PH12345',
    licenseExpiration: '2025-06-30',
    npiNumber: '1234567890',
    business_contact: 15,
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 2,
    firstname: 'Jane',
    middle_initial: 'A',
    lastname: 'Smith',
    image: user3,
    type: 'Retail Pharmacy',
    business_name: 'CVS Health',
    phone: '999-895-9652',
    email: 'janesmith@cvs.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Focus on chronic disease management',
    fax: 'AC9876543',
    licenseNumber: 'PH67890',
    licenseExpiration: '2026-03-15',
    npiNumber: '9876543210',
    business_contact: 10,
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 3,
    firstname: 'Albert',
    middle_initial: 'A',
    lastname: 'Johnson',
    image: user4,
    type: 'Compounding Pharmacy',
    business_name: 'Custom Rx',
    phone: '789-854-8950',
    email: 'ajohnson@customrx.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Expert in sterile compounding',
    fax: 'BC7654321',
    licenseNumber: 'PH09876',
    licenseExpiration: '2024-11-22',
    npiNumber: '3456789012',
    business_contact: 8,
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 4,
    firstname: 'Emily',
    middle_initial: 'A',
    lastname: 'Clark',
    image: user5,
    type: 'Clinical Pharmacy',
    business_name: 'Kaiser Permanente',
    phone: '452-652-5230',
    email: 'eclark@kp.org',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Specializes in pediatrics',
    fax: 'CD6543210',
    licenseNumber: 'PH54321',
    licenseExpiration: '2023-09-01',
    npiNumber: '5678901234',
    business_contact: 12,
    frequentlycontacted: false,
    starred: true,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 5,
    firstname: 'David',
    middle_initial: 'A',
    lastname: 'Brown',
    image: user1,
    type: 'Hospital Pharmacy',
    business_name: 'Mount Sinai Hospital',
    phone: '985-985-7850',
    email: 'dbrown@mountsinai.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Focus on emergency medicine',
    fax: 'EF6543219',
    licenseNumber: 'PH23456',
    licenseExpiration: '2027-01-12',
    npiNumber: '6543210987',
    business_contact: 18,
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 6,
    firstname: 'Sophia',
    middle_initial: 'A',
    lastname: 'Davis',
    image: user2,
    type: 'Retail Pharmacy',
    business_name: 'Rite Aid',
    phone: '230-541-5231',
    email: 'sdavis@riteaid.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Chronic care management specialist',
    fax: 'FG8765432',
    licenseNumber: 'PH76543',
    licenseExpiration: '2025-07-25',
    npiNumber: '1230987654',
    business_contact: 14,
    frequentlycontacted: true,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 7,
    firstname: 'Olivia',
    middle_initial: 'A',
    lastname: 'Miller',
    image: user3,
    type: 'Retail Pharmacy',
    business_name: 'CVS Health',
    phone: '478-582-6520',
    email: 'omiller@cvs.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Specializes in patient education',
    fax: 'GH9876543',
    licenseNumber: 'PH76544',
    licenseExpiration: '2026-08-18',
    npiNumber: '1239876543',
    business_contact: 7,
    frequentlycontacted: false,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 8,
    firstname: 'Noah',
    middle_initial: 'A',
    lastname: 'Williams',
    image: user4,
    type: 'Hospital Pharmacy',
    business_name: 'Cedars-Sinai Medical Center',
    phone: '123-652-2301',
    email: 'nwilliams@cedars-sinai.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Focus on critical care business_name',
    fax: 'HI8765432',
    licenseNumber: 'PH65432',
    licenseExpiration: '2025-12-10',
    npiNumber: '6540987654',
    business_contact: 11,
    frequentlycontacted: true,
    starred: true,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 9,
    firstname: 'Liam',
    middle_initial: 'A',
    lastname: 'Jones',
    image: user5,
    type: 'Clinical Pharmacy',
    business_name: 'Mayo Clinic',
    phone: '652-452-6521',
    email: 'ljones@mayoclinic.org',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Expert in cardiology medication',
    fax: 'IJ7654321',
    licenseNumber: 'PH54322',
    licenseExpiration: '2024-04-28',
    npiNumber: '0987654321',
    business_contact: 13,
    frequentlycontacted: false,
    starred: true,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 10,
    firstname: 'Emma',
    middle_initial: 'A',
    lastname: 'Taylor',
    image: user2,
    type: 'Compounding Pharmacy',
    business_name: 'Custom Meds',
    phone: '785-985-6541',
    email: 'etaylor@custommeds.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Specializes in hormone replacement therapy',
    fax: 'JK6543219',
    licenseNumber: 'PH43211',
    licenseExpiration: '2027-11-02',
    npiNumber: '4321098765',
    business_contact: 9,
    frequentlycontacted: false,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 11,
    firstname: 'James',
    middle_initial: 'A',
    lastname: 'Anderson',
    image: user1,
    type: 'Retail Pharmacy',
    business_name: 'Walgreens',
    phone: '652-632-6520',
    email: 'janderson@walgreens.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Diabetes management expert',
    fax: 'KL5432109',
    licenseNumber: 'PH32109',
    licenseExpiration: '2023-09-15',
    npiNumber: '7654321098',
    business_contact: 8,
    frequentlycontacted: false,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
    {
    id: 12,
    firstname: 'Charlotte',
    middle_initial: 'A',
    lastname: 'Martinez',
    image: user2,
    type: 'Hospital Pharmacy',
    business_name: 'Stanford Health Care',
    phone: '125-985-3210',
    email: 'cmartinez@stanfordhealth.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Specializes in infectious disease pharmacotherapy',
    fax: 'LM4321098',
    licenseNumber: 'PH21098',
    licenseExpiration: '2026-05-19',
    npiNumber: '8765432109',
    business_contact: 14,
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 13,
    firstname: 'Amelia',
    middle_initial: 'A',
    lastname: 'Garcia',
    image: user3,
    type: 'Clinical Pharmacy',
    business_name: 'UCLA Health',
    phone: '541-521-6320',
    email: 'agarcia@uclahealth.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Pediatric specialist',
    fax: 'MN3210987',
    licenseNumber: 'PH10987',
    licenseExpiration: '2024-12-30',
    npiNumber: '2109876543',
    business_contact: 6,
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 14,
    firstname: 'Mason',
    middle_initial: 'A',
    lastname: 'Hernandez',
    image: user4,
    type: 'Retail Pharmacy',
    business_name: 'Rite Aid',
    phone: '975-895-5240',
    email: 'mhernandez@riteaid.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Specializes in geriatric care',
    fax: 'NO2109876',
    licenseNumber: 'PH09876',
    licenseExpiration: '2025-02-14',
    npiNumber: '3210987654',
    business_contact: 5,
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 15,
    firstname: 'Isabella',
    middle_initial: 'A',
    lastname: 'Lopez',
    image: user5,
    type: 'Hospital Pharmacy',
    business_name: 'Cleveland Clinic',
    phone: '874-546-6521',
    email: 'ilopez@clevelandclinic.org',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Critical care specialist',
    fax: 'OP0987654',
    licenseNumber: 'PH98765',
    licenseExpiration: '2026-10-21',
    npiNumber: '6543210987',
    business_contact: 12,
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 16,
    firstname: 'Elijah',
    middle_initial: 'A',
    lastname: 'Gonzalez',
    image: user1,
    type: 'Compounding Pharmacy',
    business_name: 'Precision Compounds',
    phone: '652-542-5200',
    email: 'egonzalez@precisioncompounds.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Expert in custom medication formulations',
    fax: 'PQ9876543',
    licenseNumber: 'PH87654',
    licenseExpiration: '2025-06-10',
    npiNumber: '7654321098',
    business_contact: 17,
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 17,
    firstname: 'Lucas',
    middle_initial: 'A',
    lastname: 'Wilson',
    image: user2,
    type: 'Clinical Pharmacy',
    business_name: 'Johns Hopkins Hospital',
    phone: '326-984-1200',
    email: 'lwilson@jhmi.edu',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Expert in neurology pharmacotherapy',
    fax: 'QR8765432',
    licenseNumber: 'PH76543',
    licenseExpiration: '2024-11-11',
    npiNumber: '8765432109',
    business_contact: 9,
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 18,
    firstname: 'Sophia',
    middle_initial: 'A',
    lastname: 'Thomas',
    image: user3,
    type: 'Retail Pharmacy',
    business_name: 'CVS Health',
    phone: '265-632-4521',
    email: 'sthomas@cvs.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Chronic disease management',
    fax: 'RS7654321',
    licenseNumber: 'PH65432',
    licenseExpiration: '2026-01-30',
    npiNumber: '9876543210',
    business_contact: 13,
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 19,
    firstname: 'Aiden',
    middle_initial: 'A',
    lastname: 'White',
    image: user4,
    type: 'Hospital Pharmacy',
    business_name: 'NewYork-Presbyterian Hospital',
    phone: '645-647-4800',
    email: 'awhite@nyp.org',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Expert in oncology pharmacotherapy',
    fax: 'ST6543210',
    licenseNumber: 'PH54321',
    licenseExpiration: '2024-10-05',
    npiNumber: '6543210987',
    business_contact: 15,
    frequentlycontacted: false,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 20,
    firstname: 'Ethan',
    middle_initial: 'A',
    lastname: 'Harris',
    image: user5,
    type: 'Retail Pharmacy',
    business_name: 'CVS Health',
    phone: '654-985-6520',
    email: 'eharris@cvs.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Diabetes care and management',
    fax: 'UV5432109',
    licenseNumber: 'PH43210',
    licenseExpiration: '2027-03-29',
    npiNumber: '7654321098',
    business_contact: 11,
    frequentlycontacted: false,
    starred: true,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 21,
    firstname: 'Mia',
    middle_initial: 'A',
    lastname: 'Clark',
    image: user3,
    type: 'Clinical Pharmacy',
    business_name: 'Kaiser Permanente',
    phone: '456-652-3210',
    email: 'mclark@kp.org',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Expert in cardiovascular pharmacotherapy',
    fax: 'WX4321098',
    licenseNumber: 'PH32109',
    licenseExpiration: '2025-06-17',
    npiNumber: '9876543210',
    business_contact: 9,
    frequentlycontacted: true,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 22,
    firstname: 'Ava',
    middle_initial: 'A',
    lastname: 'Lewis',
    image: user1,
    type: 'Compounding Pharmacy',
    business_name: 'Precision Compounds',
    phone: '459-985-4520',
    email: 'alewis@precisioncompounds.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Expert in sterile compounding and bioidentical hormones',
    fax: 'YZ3210987',
    licenseNumber: 'PH21098',
    licenseExpiration: '2026-02-12',
    npiNumber: '8765432109',
    business_contact: 14,
    frequentlycontacted: true,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 23,
    firstname: 'Logan',
    middle_initial: 'A',
    lastname: 'Walker',
    image: user2,
    type: 'Hospital Pharmacy',
    business_name: 'Massachusetts General Hospital',
    phone: '645-978-4150',
    email: 'lwalker@mgh.org',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Pediatric pharmacotherapy specialist',
    fax: 'ZA2109876',
    licenseNumber: 'PH10987',
    licenseExpiration: '2025-10-01',
    npiNumber: '6543210987',
    business_contact: 10,
    frequentlycontacted: true,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
    {
    id: 24,
    firstname: 'Lucas',
    middle_initial: 'A',
    lastname: 'King',
    image: user3,
    type: 'Retail Pharmacy',
    business_name: 'Rite Aid',
    phone: '450-980-6520',
    email: 'lking@riteaid.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Chronic care management and medication adherence specialist',
    fax: 'AB1234567',
    licenseNumber: 'PH98765',
    licenseExpiration: '2026-07-21',
    npiNumber: '5432109876',
    business_contact: 13,
    frequentlycontacted: false,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 25,
    firstname: 'Harper',
    middle_initial: 'A',
    lastname: 'Scott',
    image: user4,
    type: 'Clinical Pharmacy',
    business_name: 'Mayo Clinic',
    phone: '120-320-4520',
    email: 'hscott@mayoclinic.org',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Focus on neuropharmacology',
    fax: 'BC2345678',
    licenseNumber: 'PH87654',
    licenseExpiration: '2024-11-30',
    npiNumber: '2109876543',
    business_contact: 17,
    frequentlycontacted: true,
    starred: true,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 26,
    firstname: 'Ella',
    middle_initial: 'A',
    lastname: 'Young',
    image: user4,
    type: 'Hospital Pharmacy',
    business_name: 'Mount Sinai Hospital',
    phone: '452-521-1230',
    email: 'eyoung@mountsinai.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Specialist in infectious diseases',
    fax: 'CD3456789',
    licenseNumber: 'PH76543',
    licenseExpiration: '2023-08-15',
    npiNumber: '4321098765',
    business_contact: 11,
    frequentlycontacted: false,
    starred: false,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 27,
    firstname: 'William',
    middle_initial: 'A',
    lastname: 'Hall',
    image: user5,
    type: 'Compounding Pharmacy',
    business_name: 'CustomRx',
    phone: '652-452-1230',
    email: 'whall@customrx.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Expert in compounding sterile preparations',
    fax: 'DE4567890',
    licenseNumber: 'PH65432',
    licenseExpiration: '2026-04-12',
    npiNumber: '5432109876',
    business_contact: 15,
    frequentlycontacted: false,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 28,
    firstname: 'Grace',
    middle_initial: 'A',
    lastname: 'Allen',
    image: user1,
    type: 'Retail Pharmacy',
    business_name: 'Walgreens',
    phone: '963-652-1230',
    email: 'gallen@walgreens.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Specializes in geriatric medication management',
    fax: 'EF5678901',
    licenseNumber: 'PH54321',
    licenseExpiration: '2024-05-20',
    npiNumber: '4321098765',
    business_contact: 7,
    frequentlycontacted: true,
    starred: true,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 29,
    firstname: 'Benjamin',
    middle_initial: 'A',
    lastname: 'Lopez',
    image: user2,
    type: 'Hospital Pharmacy',
    business_name: 'Cleveland Clinic',
    phone: '546-654-1230',
    email: 'blopez@clevelandclinic.org',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Oncology pharmacist specializing in chemotherapy',
    fax: 'FG6789012',
    licenseNumber: 'PH43210',
    licenseExpiration: '2025-08-30',
    npiNumber: '3210987654',
    business_contact: 18,
    frequentlycontacted: false,
    starred: false,
    deleted: false,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  },
  {
    id: 30,
    firstname: 'Chloe',
    middle_initial: 'A',
    lastname: 'Hernandez',
    image: user1,
    type: 'Clinical Pharmacy',
    business_name: 'UCLA Health',
    phone: '123-456-7890',
    email: 'chernandez@uclahealth.com',
    address: '19214 110th Rd',
    address2: '',
    city: 'Saint Albans',
    state: 'NY',
    zipcode: '11412',
    notes: 'Clinical research specialist in pharmacology',
    fax: 'GH7890123',
    licenseNumber: 'PH32109',
    licenseExpiration: '2026-09-05',
    npiNumber: '6543210987',
    business_contact: 12,
    frequentlycontacted: false,
    starred: true,
    deleted: true,
    pharmacies: [201, 202],
    users: 4,
    patients: 4,
    requests: 8,
    faxes: [201, 202],
  }
];
mock.onGet('/api/data/physicians/PhysiciansData').reply(() => {
  const physicians = PhysicianList;
  return [200, JSON.parse(JSON.stringify(physicians))];
});
export default PhysicianList;
